<script setup lang="ts">
import{computed,ref,watch,nextTick,onMounted,onBeforeUnmount}from'vue';import{useRoute,useRouter}from'vue-router';import{ElMessageBox}from'element-plus';import{session,logout}from'./session';import{routes}from'./router';import{routeForMenu,allowedMenu}from'./navigation';import MenuBranch from'./components/MenuBranch.vue';import LoginForm from'./components/LoginForm.vue';
const pageLoadFailed=ref(false);const pageFailure=()=>{pageLoadFailed.value=true};const reloadPage=()=>window.location.reload();onMounted(()=>window.addEventListener('sf-page-load-failed',pageFailure));onBeforeUnmount(()=>window.removeEventListener('sf-page-load-failed',pageFailure));
const route=useRoute(),router=useRouter(),collapsed=ref(false),mobileMenu=ref(false),content=ref<HTMLElement>();const resolve=computed(()=>routeForMenu(session.menus,routes));
const tabs=ref<{path:string;title:string}[]>([]),scrolls=new Map<string,number>();let active='';const isPublic=computed(()=>!!route.meta.public);
watch(()=>[route.fullPath,route.meta.title],async ([rawPath])=>{const path=String(rawPath);if(content.value&&active)scrolls.set(active,content.value.scrollTop);active=path;if(!isPublic.value&&route.matched.length){const suffix=route.meta.coreMode==='new'?' · 新增':route.meta.coreMode==='edit'?' · 编辑':route.meta.coreMode==='detail'?' · 详情':'';const title=String(route.meta.title||'业务页面')+suffix;const existing=tabs.value.find(x=>x.path===path);if(existing)existing.title=title;else tabs.value.push({path,title})}mobileMenu.value=false;await nextTick();if(content.value)content.value.scrollTop=scrolls.get(path)||0},{immediate:true});
async function closeTab(path:string){if(path===route.fullPath){const next=tabs.value.find(x=>x.path!==path)?.path||'/';await router.push(next);if(route.fullPath===path)return}tabs.value=tabs.value.filter(x=>x.path!==path)}
async function signOut(){try{await ElMessageBox.confirm('退出当前账号？未保存的录入请先保存。','退出登录');await router.push('/login');if(route.path!=='/login')return;logout();tabs.value=[]}catch{}}
const canView=computed(()=>session.authenticated&&session.loaded&&allowedMenu(route.meta.menuPath as string|undefined,session.menus))
async function recovered(){if(!canView.value){await nextTick();await router.replace('/forbidden')}}
async function freshLogin(){await router.replace('/')}
watch(()=>session.viewVersion,()=>{scrolls.clear();tabs.value=session.identityChanged?[]:tabs.value.filter(tab=>allowedMenu(router.resolve(tab.path).meta.menuPath as string|undefined,session.menus))},{flush:'sync'})
watch(()=>[session.identityChanged,session.loaded,canView.value],async()=>{if(!isPublic.value&&session.loaded&&!session.identityChanged&&!canView.value){await nextTick();await router.replace('/forbidden')}})
const size=ref(window.innerWidth);
const resize=()=>{size.value=window.innerWidth;if(size.value>=900)mobileMenu.value=false};
const dismissMenu=(event:KeyboardEvent)=>{if(event.key==='Escape')mobileMenu.value=false};
watch(mobileMenu,async open=>{await nextTick();if(size.value<900)document.querySelector<HTMLElement>(open?'#workspace-navigation a':'.menu-toggle')?.focus()});
onMounted(()=>{window.addEventListener('resize',resize);window.addEventListener('keydown',dismissMenu)});
onBeforeUnmount(()=>{window.removeEventListener('resize',resize);window.removeEventListener('keydown',dismissMenu)});
</script>
<template><el-dialog v-model="pageLoadFailed" title="页面加载失败" width="420px"><p>页面资源未能加载。请先保留当前草稿，再手动重新加载；尚未提交的内容不会自动保存。</p><template #footer><el-button @click="pageLoadFailed=false">返回当前页面</el-button><el-button type="primary" @click="reloadPage">重新加载</el-button></template></el-dialog><router-view v-if="isPublic"/><section v-else-if="session.identityChanged" class="login-screen"><main><div class="login-box"><h2>请重新登录</h2><p>{{session.error}}</p><LoginForm @success="freshLogin"/></div></main></section><div v-else class="app-shell" :class="{'is-collapsed':collapsed,'menu-open':mobileMenu}"><button v-if="mobileMenu" class="sidebar-mask" aria-label="关闭导航菜单" @click="mobileMenu=false"/><aside id="workspace-navigation" class="sidebar" :inert="size<900&&!mobileMenu?true:undefined" aria-label="主导航"><button class="sidebar-close" aria-label="关闭菜单" @click="mobileMenu=false">×</button><router-link to="/" class="brand"><b>SF</b><span v-if="!collapsed||size<900">业务管理工作台</span></router-link><div class="sidebar-caption" v-if="!collapsed||size<900">WORKSPACE</div><el-scrollbar><el-menu :default-active="route.path" :collapse="collapsed&&size>=900" :collapse-transition="false" router><MenuBranch :items="session.menus" :resolve="resolve"/></el-menu></el-scrollbar><div class="sidebar-footer"><span>清晰记录 · 有序协作</span></div></aside><section class="workspace" :inert="size<900&&mobileMenu?true:undefined"><header class="topbar"><el-button text class="menu-toggle" aria-controls="workspace-navigation" :aria-expanded="size<900?mobileMenu:!collapsed" aria-label="展开或收起菜单" @click="size<900?mobileMenu=!mobileMenu:collapsed=!collapsed">☰</el-button><span class="mobile-page-title">{{route.meta.title}}</span><el-breadcrumb><el-breadcrumb-item>工作台</el-breadcrumb-item><el-breadcrumb-item>{{route.meta.title}}</el-breadcrumb-item></el-breadcrumb><div class="topbar-right"><a href="/m/">手机端</a><a href="/legacy/">旧版后台</a><span>{{session.userName}}</span><el-button text @click="router.push('/profile')">个人资料</el-button><el-button text @click="signOut">退出</el-button></div></header><nav class="tabs-bar" aria-label="已打开的页面"><div v-for="tab in tabs" :key="tab.path" class="workspace-tab" :class="{active:tab.path===route.fullPath}"><button @click="router.push(tab.path)">{{tab.title}}</button><button v-if="tabs.length>1" :aria-label="'关闭'+tab.title" @click="closeTab(tab.path)">×</button></div></nav><main ref="content" class="workspace-content"><el-result v-if="!canView" icon="warning" title="当前页面无访问权限"/><router-view v-else v-slot="{Component}"><keep-alive :key="session.viewVersion" :max="40"><component :is="Component" :key="route.path"/></keep-alive></router-view></main></section><el-dialog v-model="session.expired" title="登录已过期" width="420px" :close-on-click-modal="false" :close-on-press-escape="false" :show-close="false"><p>当前表单已保留，请重新登录后继续。提交结果不明时请先核对记录。</p><LoginForm :fixed-user="session.userName" @success="recovered"/></el-dialog></div></template>
