// @vitest-environment jsdom
import {beforeEach,afterEach,expect,test,vi} from 'vitest'
import {request,bindAccessToken} from './api'
import {session,loadSession,login,logout} from './session'
import {allowedMenu} from './navigation'
import systemRoutes from './modules/system/routes'
const menuA=[{id:1,title:'用户',href:'/system/user/index.html'}]
function response(data:any){return new Response(JSON.stringify(data),{status:200,headers:{'Content-Type':'application/json'}})}
function useToken(token='token-A'){localStorage.setItem('access_token',token);bindAccessToken(token);session.authenticated=true}
function server(menu:any[]=menuA,id=1,username='actual-A'){vi.mocked(fetch).mockImplementation(async(input)=>response(String(input).endsWith('/menu')?menu:String(input).endsWith('/login')?{code:0,access_token:'refreshed-A'}:{code:0,data:{id,username}}))}
beforeEach(()=>{localStorage.clear();logout();vi.stubGlobal('fetch',vi.fn())})
afterEach(()=>{logout();vi.unstubAllGlobals()})
test('legacy token bootstrap uses authoritative profile instead of cached username',async()=>{useToken();localStorage.setItem('sf-desktop-username','stale-name');server();await loadSession();expect(session.userName).toBe('actual-A');expect(session.userId).toBe(1);expect(session.loaded).toBe(true)})
test('token replacement blocks write before network and invalidates cached identity',async()=>{useToken();session.userId=1;session.userName='A';session.menus=menuA;session.loaded=true;const version=session.viewVersion;localStorage.setItem('access_token','token-B');await expect(request('/user/7',{method:'PUT',body:'{}'})).rejects.toThrow('账号已在其他页面改变');expect(fetch).not.toHaveBeenCalled();expect(session.identityChanged).toBe(true);expect(session.authenticated).toBe(false);expect(session.menus).toEqual([]);expect(session.viewVersion).toBeGreaterThan(version)})
test('storage logout immediately invalidates old identity and draft cache',()=>{useToken();session.userId=1;localStorage.removeItem('access_token');window.dispatchEvent(new StorageEvent('storage',{key:'access_token',oldValue:'token-A',newValue:null}));expect(session.identityChanged).toBe(true);expect(session.userId).toBe(null)})
test('token replacement during response discards returned old-account data',async()=>{useToken();let release!:(value:Response)=>void;vi.mocked(fetch).mockImplementation(()=>new Promise(resolve=>release=resolve));const pending=request('/order/7');localStorage.setItem('access_token','token-B');release(response({code:0,data:{secret:'A'}}));await expect(pending).rejects.toThrow('账号已在其他页面改变');expect(session.identityChanged).toBe(true)})
test('same-user reauthentication keeps cache version and resolves expiry',async()=>{useToken();server();await loadSession();session.expired=true;const version=session.viewVersion;await login('actual-A','password');expect(session.userId).toBe(1);expect(session.expired).toBe(false);expect(session.viewVersion).toBe(version);const loginCall=vi.mocked(fetch).mock.calls.find(call=>String(call[0]).endsWith('/login'))!;expect(new Headers(loginCall[1]?.headers).has('Authorization')).toBe(false)})
test('removed menu grants invalidate cached pages during recovery',async()=>{useToken();server();await loadSession();const version=session.viewVersion;server([]);await loadSession();expect(session.viewVersion).toBeGreaterThan(version);expect(allowedMenu('/system/user/index.html',session.menus)).toBe(false)})
test('a different authoritative identity cannot inherit the former session',async()=>{useToken();server();await loadSession();server(menuA,2,'B');await expect(loadSession()).rejects.toThrow('登录账号已改变');expect(session.identityChanged).toBe(true);expect(session.authenticated).toBe(false)})
test('public token portal never sends bearer and works after unrelated token replacement',async()=>{useToken();localStorage.setItem('access_token','token-B');vi.mocked(fetch).mockResolvedValue(response({code:0,data:{supplier:{name:'Public'}}}));await request('/portal/reconcile/secret/data');expect(new Headers(vi.mocked(fetch).mock.calls[0][1]?.headers).has('Authorization')).toBe(false)})
test('own profile requires authentication but no menu grant',()=>{const profile=systemRoutes.find(route=>route.path==='/profile')!;expect(profile.meta?.public).not.toBe(true);expect(allowedMenu(profile.meta?.menuPath as string,[])).toBe(true)})
test('write result becomes uncertain when identity changes after submission',async()=>{useToken();let release!:(value:Response)=>void;vi.mocked(fetch).mockImplementation(()=>new Promise(resolve=>release=resolve));const pending=request('/pay/',{method:'POST',body:'{}'});localStorage.setItem('access_token','token-B');release(response({code:0,data:{id:99}}));await expect(pending).rejects.toMatchObject({uncertain:true});expect(fetch).toHaveBeenCalledTimes(1)})
test('trusted same-user token renewal discards older response without forcing new login',async()=>{useToken();let release!:(value:Response)=>void;vi.mocked(fetch).mockImplementation(()=>new Promise(resolve=>release=resolve));const pending=request('/order/1');localStorage.setItem('access_token','renewed-A');bindAccessToken('renewed-A');release(response({code:0,data:{id:1}}));await expect(pending).rejects.toThrow('旧请求结果已丢弃');expect(session.identityChanged).toBe(false)})

test('loads the nickname separately from the login name and clears it on logout',async()=>{useToken();vi.mocked(fetch).mockImplementation(async(input)=>response(String(input).endsWith('/menu')?menuA:{code:0,data:{id:1,username:'admin',nickname:'材料管理员'}}));await loadSession();expect(session.nickname).toBe('材料管理员');expect(session.userName).toBe('admin');logout();expect(session.nickname).toBe('')})
