// @vitest-environment jsdom
import {describe,it,expect,vi,beforeEach} from 'vitest'
import {mount,flushPromises} from '@vue/test-utils'
import {createRouter,createMemoryHistory} from 'vue-router'
import CorePage from './CorePage.vue'
const mocks=vi.hoisted(()=>({request:vi.fn(),allRows:vi.fn(),confirm:vi.fn()}))
vi.mock('../../api',()=>({request:mocks.request,allRows:mocks.allRows,query:(p:any)=>new URLSearchParams(p).toString(),safeUrl:(p:any)=>p||''}))
vi.mock('element-plus',()=>({ElMessage:{error:vi.fn(),success:vi.fn(),warning:vi.fn()},ElMessageBox:{confirm:mocks.confirm}}))
vi.mock('../../components/AttachmentEditor.vue',()=>({default:{props:['modelValue'],template:'<div />'}}))
const input={props:['modelValue'],emits:['update:modelValue'],template:'<input :value="modelValue" @input="$emit(\'update:modelValue\',$event.target.value)" />'}
const stubs:any={'el-form':{template:'<form><slot/></form>'},'el-form-item':{props:['label'],template:'<label>{{label}}<slot/></label>'},'el-input':input,'el-select':input,'el-option':true,'el-date-picker':input,'el-button':{props:['nativeType','disabled','loading'],template:'<button :type="nativeType||\'button\'" :disabled="disabled||loading"><slot/></button>'},'el-alert':{props:['title'],template:'<div role="alert">{{title}}</div>'},'el-dialog':true,'el-table':true,'el-table-column':true,'el-pagination':true,'el-descriptions':true,'el-descriptions-item':true,'el-popover':true,'el-checkbox-group':true,'el-checkbox':true,'el-empty':{props:['description'],template:'<p>{{description}}</p>'}}
async function setup(){const router=createRouter({history:createMemoryHistory(),routes:[{path:'/projects/new',component:CorePage,meta:{coreKind:'projects',coreMode:'new'}},{path:'/projects',component:{template:'<div>项目列表</div>'}},{path:'/system',component:{template:'<div>系统页面</div>'}}]});await router.push('/projects/new');await router.isReady();const wrapper=mount({template:'<router-view v-slot="{Component,route}"><keep-alive><component :is="Component" :key="route.path"/></keep-alive></router-view>'},{global:{plugins:[router],stubs,directives:{loading:()=>{}}}});await flushPromises();return{wrapper,router}}
describe('core form operation behavior',()=>{
 beforeEach(()=>{vi.clearAllMocks();mocks.request.mockResolvedValue({code:0,data:{}});mocks.allRows.mockResolvedValue([]);mocks.confirm.mockResolvedValue('confirm')})
 it('submits a decimal string once while pending then leaves only after success',async()=>{const {wrapper,router}=await setup();await wrapper.find('label input').setValue('新项目');const amount=wrapper.findAll('label').find(x=>x.text().includes('合同金额'))!;await amount.find('input').setValue('123.45');let resolve:any;mocks.request.mockImplementation(()=>new Promise(r=>resolve=r));await wrapper.find('form').trigger('submit');await wrapper.find('form').trigger('submit');expect(mocks.request).toHaveBeenCalledTimes(2); // initial dictionary read + exactly one POST
 const call=mocks.request.mock.calls[1]!;expect(call[0]).toBe('/project/');expect(JSON.parse(call[1].body).project_amount).toBe('123.45');expect(router.currentRoute.value.path).toBe('/projects/new');resolve({code:0,data:{id:7}});await flushPromises();expect(router.currentRoute.value.path).toBe('/projects');await router.push('/projects/new');await flushPromises();expect(wrapper.find('label input').element).toHaveProperty('value','');expect(wrapper.findAll('label').find(x=>x.text().includes('合同金额'))!.find('input').element).toHaveProperty('value','');wrapper.unmount()})
 it('keeps the draft visible and editable after a server failure',async()=>{const {wrapper,router}=await setup();await wrapper.find('label input').setValue('保留草稿');mocks.request.mockRejectedValueOnce(new Error('网络失败'));await wrapper.find('form').trigger('submit');await flushPromises();expect(wrapper.find('label input').element).toHaveProperty('value','保留草稿');expect(wrapper.text()).toContain('网络失败');expect(router.currentRoute.value.path).toBe('/projects/new');expect(wrapper.findAll('button').find(x=>x.text()==='保存')!.attributes('disabled')).toBeUndefined();wrapper.unmount()})
 it('does not reset cached drafts or request a different module after navigation',async()=>{const {wrapper,router}=await setup();await wrapper.find('label input').setValue('缓存草稿');const calls=mocks.request.mock.calls.length;await router.push('/system');await flushPromises();expect(wrapper.text()).toContain('系统页面');expect(mocks.request).toHaveBeenCalledTimes(calls);await router.push('/projects/new');await flushPromises();expect(wrapper.find('label input').element).toHaveProperty('value','缓存草稿');expect(mocks.request).toHaveBeenCalledTimes(calls);wrapper.unmount()})
 it('shows a no-file empty state and Chinese OCR state for manually entered invoices',async()=>{mocks.request.mockImplementation(async(path:string)=>({code:0,data:path.startsWith('/material/invoice?')?[{id:1,invoice_number:'MANUAL1',ocr_status:'pending',file_path:null,file_url:null}]:{}}));const router=createRouter({history:createMemoryHistory(),routes:[{path:'/invoices/:id',component:CorePage,meta:{coreKind:'invoices',coreMode:'detail'}}]});await router.push('/invoices/1');await router.isReady();const wrapper=mount({template:'<router-view />'},{global:{plugins:[router],stubs,directives:{loading:()=>{}}}});await flushPromises();expect(wrapper.text()).toContain('此发票尚未上传原文件');expect(wrapper.text()).toContain('待识别');expect(wrapper.find('a[href=""]').exists()).toBe(false);expect(wrapper.find('object').exists()).toBe(false);wrapper.unmount()})
})


