<script setup lang="ts">
import {computed} from 'vue'
import {invoiceAmounts, invoiceTotal, type Row} from './model'
import {uppercaseMoney} from './money'
const props=defineProps<{invoice:Row}>()
const total=computed(()=>invoiceTotal(props.invoice))
const amounts=computed(()=>invoiceAmounts(props.invoice))
const columns=[['name','货物或应税劳务、服务名称'],['spec','规格型号'],['unit','单位'],['quantity','数量'],['price','单价'],['amount','金额'],['tax_rate','税率'],['tax','税额']]
const details=computed(()=>{if(Array.isArray(props.invoice.details))return props.invoice.details;if(props.invoice.details_json){try{const list=JSON.parse(props.invoice.details_json);return Array.isArray(list)?list:[]}catch{return []}}return []})
</script>
<template><article class="invoice-paper" aria-label="发票票面"><header class="invoice-meta"><div><p>发票代码：<b>{{invoice.invoice_code||'—'}}</b></p><p>发票号码：<b class="number">{{invoice.invoice_number||'—'}}</b></p></div><div><p>机器编号：<b>{{invoice.machine_num||'—'}}</b></p><p>校验码：<b>{{invoice.check_code||'—'}}</b></p><p>开票日期：<b>{{invoice.invoice_date||'—'}}</b></p></div></header><h2>{{invoice.invoice_name||invoice.invoice_type||'增值税发票'}}</h2>
<div class="invoice-box"><div class="parties"><section v-for="party in [{key:'buyer',label:'购买方'},{key:'seller',label:'销售方'}]" :key="party.key" class="party"><div class="vertical-label">{{party.label}}</div><div class="party-fields"><p><label>名称</label><strong>{{invoice[party.key+'_name']||'—'}}</strong></p><p><label>纳税人识别号</label><b class="tax-number">{{invoice[party.key+'_tax_num']||'—'}}</b></p><p><label>地址、电话</label><span>{{invoice[party.key+'_address_phone']||'—'}}</span></p><p><label>开户行及账号</label><span>{{invoice[party.key+'_bank_account']||'—'}}</span></p></div></section></div>
<div class="invoice-items"><table><thead><tr><th v-for="[key,label] in columns" :key="key">{{label}}</th></tr></thead><tbody><tr v-for="(item,index) in details" :key="item.id||index"><td v-for="[key] in columns" :key="key">{{key==='tax'?(item.tax??item.tax_amount):item[key!]}}</td></tr><tr v-if="!details.length"><td colspan="8" class="empty">暂无识别明细</td></tr></tbody><tfoot><tr><th colspan="5">合计（不含税金额 / 税额）</th><td>{{amounts.untaxed}}</td><td></td><td>{{amounts.tax}}</td></tr></tfoot></table></div>
<div class="invoice-total"><label>价税合计（大写）</label><strong>{{total === null ? '待核实' : (invoice.amount_in_words||uppercaseMoney(total))}}</strong><span>价税合计（小写）<b>{{amounts.total}}</b></span></div><div class="invoice-remarks"><div class="vertical-label">备注</div><p>{{invoice.remarks||'—'}}</p></div></div>
<footer><span>收款人：{{invoice.payee||'—'}}</span><span>复核：{{invoice.checker||'—'}}</span><span>开票人：{{invoice.drawer||'—'}}</span><span>销售方：（章）</span></footer></article></template>
<style scoped>.invoice-paper{font-family:SimSun,'Songti SC',serif;background:white;padding:32px;margin:20px 0;border:1px solid #e5ded8;border-radius:8px;color:#333;overflow-x:auto}.invoice-meta{display:flex;justify-content:space-between;gap:25px;color:#888;font-size:14px}.invoice-meta p{margin:4px 0}.invoice-meta b{font-family:'Courier New',monospace;color:#222;letter-spacing:1px}.invoice-meta .number,.tax-number{color:#16866b}.invoice-meta .number{font-size:18px}.invoice-paper h2{text-align:center;color:#b65e49;font-size:28px;text-decoration:underline double;text-underline-offset:9px;letter-spacing:3px;margin:28px 0}.invoice-box{border:2px solid #b65e49;min-width:700px}.parties{display:grid;grid-template-columns:1fr 1fr;border-bottom:1px solid #b65e49}.party{display:flex}.party+.party{border-left:1px solid #b65e49}.vertical-label{writing-mode:vertical-rl;text-align:center;padding:12px 8px;border-right:1px solid #b65e49;color:#b65e49;letter-spacing:5px;flex-shrink:0}.party-fields{padding:8px;flex:1;min-width:0}.party-fields p{display:flex;font-size:13px;margin:6px 0;line-height:1.6}.party-fields label{width:100px;flex-shrink:0;color:#b65e49}.party-fields span,.party-fields strong,.party-fields b{overflow-wrap:anywhere}.invoice-items{min-height:150px}table{width:100%;border-collapse:collapse;table-layout:fixed;font-size:12px}th,td{border:1px solid #d5a99c;padding:9px 5px;text-align:center;overflow-wrap:anywhere}th{color:#b65e49;font-weight:500}th:first-child{width:24%}.empty{height:65px;color:#999}.invoice-total{display:flex;align-items:center;gap:20px;border-top:1px solid #b65e49;padding:12px;font-size:14px}.invoice-total label{color:#b65e49}.invoice-total strong{flex:1}.invoice-total b{font-size:17px}.invoice-remarks{display:flex;border-top:1px solid #b65e49;min-height:65px}.invoice-remarks p{white-space:pre-wrap;padding:10px;overflow-wrap:anywhere;margin:0}footer{display:flex;justify-content:space-between;gap:15px;margin-top:18px;font-size:14px}@media print{.invoice-paper{padding:0;border:0;overflow:visible}.invoice-box{min-width:0}}</style>
