// @vitest-environment jsdom
import {mount, flushPromises} from '@vue/test-utils'
import {describe, it, expect, vi, beforeEach} from 'vitest'
import PaymentInvoicePicker from './PaymentInvoicePicker.vue'
import InvoicePaymentLinks from './InvoicePaymentLinks.vue'
const mocks=vi.hoisted(()=>({request:vi.fn()}))
vi.mock('../../api',()=>({request:mocks.request}))
const global={stubs:{'el-dialog':{props:['modelValue','title'],template:'<section v-if="modelValue" role="dialog" :aria-label="title"><slot/><slot name="footer"/></section>'},'el-button':{props:['disabled','loading'],template:'<button :disabled="disabled||loading"><slot/></button>'},RouterLink:{props:['to'],template:'<a :href="to"><slot/></a>'}}}

describe('seller matched invoice/payment selections',()=>{
 beforeEach(()=>vi.resetAllMocks())
 it.each([
  ['100','13','¥113.00','¥100.00','¥13.00'],
  ['100','0','¥100.00','¥100.00','¥0.00'],
  ['-100','-13','¥-113.00','¥-100.00','¥-13.00'],
  ['0.004','0.004','¥0.01','¥0.00','¥0.00'],
  [null,'13','待核实','待核实','¥13.00'],
  ['100','invalid','待核实','¥100.00','待核实'],
 ])('shows labeled amounts in selected rows and candidates (%s, %s)',async(total_amount,tax_amount,total,untaxed,tax)=>{
  const wrapper=mount(PaymentInvoicePicker,{props:{modelValue:[1],supplierName:'甲公司',invoices:[{id:1,invoice_number:'AMOUNT',seller_name:'甲公司',total_amount,tax_amount}]},global})
  await wrapper.get('[data-testid="choose-invoices"]').trigger('click')
  expect(wrapper.findAll('.invoice-choice')).toHaveLength(2)
  for(const choice of wrapper.findAll('.invoice-choice')){
   expect(choice.text()).toContain(`价税合计`);expect(choice.text()).toContain(total)
   expect(choice.text()).toContain(`不含税金额`);expect(choice.text()).toContain(untaxed)
   expect(choice.text()).toContain(`税额`);expect(choice.text()).toContain(tax)
  }
  expect(wrapper.get('header').text()).toContain(total)
  expect(wrapper.text()).not.toContain('NaN')
  expect(wrapper.emitted('update:modelValue')).toBeUndefined()
  wrapper.unmount()
 })
 it('marks an unavailable selected invoice as unverified in the selected total',()=>{
  const wrapper=mount(PaymentInvoicePicker,{props:{modelValue:[1,2],invoices:[{id:1,total_amount:'100',tax_amount:'13'}]},global})
  expect(wrapper.get('header').text()).toContain('待核实')
  wrapper.unmount()
 })
 it('reuses existing invoices once alongside new uploads and keeps genuine failures visible',async()=>{
  mocks.request.mockResolvedValue({code:0,data:{uploaded:1,existing:2,failed:1,invoices:[{id:9,invoice_number:'NEW',ocr_status:'success'},{id:8,invoice_number:'OLD',ocr_status:'completed',existing:true},{id:8,invoice_number:'OLD',ocr_status:'completed',existing:true}],errors:[{name:'失败.pdf',reason:'文件损坏'}]}})
  const wrapper=mount(PaymentInvoicePicker,{props:{modelValue:[8],invoices:[{id:8,invoice_number:'OLD'}]},global})
  await wrapper.get('.payment-invoice-picker').trigger('drop',{dataTransfer:{files:[new File(['pdf'],'发票.pdf')]}})
  await flushPromises()
  expect(wrapper.emitted('update:modelValue')).toEqual([[[8,9]]])
  expect(wrapper.get('[role="status"]').text()).toContain('已存在 1 张，已选中')
  expect(wrapper.get('[role="status"]').text()).toContain('新上传 1 张')
  expect(wrapper.get('[role="status"]').text()).not.toContain('尚未识别完成')
  expect(wrapper.get('[role="alert"]').text()).toBe('失败.pdf：文件损坏')
  wrapper.unmount()
 })
 it('links only successful uploads, deduplicates IDs and reports invalid files and partial failures',async()=>{
  mocks.request.mockResolvedValue({code:0,data:{uploaded:2,failed:1,invoices:[{id:8,file_name:'已有.pdf',ocr_status:'success'},{id:9,file_name:'新票.png',ocr_status:'failed'}],errors:[{name:'重复.pdf',reason:'发票已存在'}]}})
  const wrapper=mount(PaymentInvoicePicker,{props:{modelValue:[8],invoices:[{id:8,invoice_number:'OLD'}]},global})
  const file=new File(['pdf'],'已有.pdf'),image=new File(['png'],'新票.png')
  await wrapper.get('.payment-invoice-picker').trigger('drop',{dataTransfer:{files:[file,file,image,new File(['x'],'不支持.txt'),new File([],'空.pdf')]}})
  await flushPromises()
  expect(mocks.request.mock.calls[0]![1].body.getAll('files')).toEqual([file,image])
  expect(wrapper.emitted('update:modelValue')).toEqual([[[8,9]]])
  expect(wrapper.get('[role="status"]').text()).toContain('尚未识别完成')
  expect(wrapper.get('[role="alert"]').text()).toContain('发票已存在')
  expect(wrapper.get('[role="alert"]').text()).toContain('不支持.txt')
  expect(wrapper.get('[role="alert"]').text()).toContain('空.pdf')
  wrapper.unmount()
 })
 it('accepts file selection, prevents concurrent uploads and keeps original links on failure',async()=>{
  let reject!:(cause:Error)=>void
  mocks.request.mockImplementationOnce(()=>new Promise((_,r)=>reject=r))
  const wrapper=mount(PaymentInvoicePicker,{props:{modelValue:[8],invoices:[{id:8,invoice_number:'OLD'}]},global})
  const input=wrapper.get('input[type="file"]'),file=new File(['pdf'],'发票.pdf')
  Object.defineProperty(input.element,'files',{value:[file],configurable:true})
  await input.trigger('change')
  await wrapper.get('.payment-invoice-picker').trigger('drop',{dataTransfer:{files:[file]}})
  expect(mocks.request).toHaveBeenCalledTimes(1)
  expect(wrapper.get('[aria-label="移除发票 OLD"]').attributes('disabled')).toBeDefined()
  reject(new Error('连接中断，提交结果尚未确认。请先核对列表，勿重复提交。'));await flushPromises()
  expect(wrapper.emitted('update:modelValue')).toBeUndefined()
  expect(wrapper.get('[role="alert"]').text()).toContain('请先核对列表')
  expect(wrapper.emitted('busy')).toEqual([[true],[false]])
  expect(wrapper.get('[data-testid="payment-invoice-dropzone"]').attributes('disabled')).toBeUndefined()
  expect(wrapper.text()).toContain('OLD')
  await wrapper.setProps({disabled:true})
  await wrapper.get('.payment-invoice-picker').trigger('drop',{dataTransfer:{files:[file]}})
  expect(mocks.request).toHaveBeenCalledTimes(1)
  wrapper.unmount()
 })
 it('matches only the raw supplier and seller names and waits for the user to choose',async()=>{
  const wrapper=mount(PaymentInvoicePicker,{props:{modelValue:[],supplierName:'杭州雅鸿装饰工程有限公司',invoices:[{id:1,invoice_number:'MATCH-001',seller_name:'杭州雅鸿装饰工程有限公司'},{id:2,invoice_number:'COMBINED',seller_name:'杭州雅鸿装饰工程有限公司（钱顺怡）'},{id:3,invoice_number:'PARTIAL',seller_name:'杭州雅鸿装饰工程有限公司分公司'},{id:4,invoice_number:'CONTACT',seller_name:'钱顺怡'},{id:5,invoice_number:'BUYER',seller_name:'无关公司',buyer_name:'杭州雅鸿装饰工程有限公司'}]},global})
  await wrapper.get('[data-testid="choose-invoices"]').trigger('click')
  expect(wrapper.get('[role="dialog"]').findAll('input[type="checkbox"]')).toHaveLength(1)
  expect((wrapper.get('[aria-label="关联发票 MATCH-001"]').element as HTMLInputElement).checked).toBe(false)
  await wrapper.get('[aria-label="关联发票 MATCH-001"]').setValue(true)
  await wrapper.get('[data-testid="confirm-invoice-selection"]').trigger('click')
  expect(wrapper.emitted('update:modelValue')).toEqual([[[1]]])
  wrapper.unmount()
 })
 it('filters exact seller matches without automatically selecting or deleting existing links',async()=>{
  const wrapper=mount(PaymentInvoicePicker,{props:{modelValue:[3],supplierName:'上海（甲）公司',invoices:[
   {id:1,seller_name:'上海（甲）公司',invoice_number:'MATCH',total_amount:'100',tax_amount:'13'},
   {id:2,seller_name:'上海（乙）公司',invoice_number:'OTHER'},
   {id:3,seller_name:'旧单位',invoice_number:'EXISTING'},
  ]},global})
  expect(wrapper.find('[role="dialog"]').exists()).toBe(false)
  await wrapper.get('[data-testid="choose-invoices"]').trigger('click')
  expect(wrapper.get('[role="dialog"]').text()).toContain('MATCH');expect(wrapper.text()).toContain('EXISTING');expect(wrapper.text()).not.toContain('OTHER')
  expect(wrapper.get('[role="dialog"]').findAll('input[type="checkbox"]').length).toBe(1)
  expect((wrapper.get('[aria-label="关联发票 MATCH"]').element as HTMLInputElement).checked).toBe(false)
  expect(wrapper.text()).toContain('113.00')
  await wrapper.get('[aria-label="关联发票 MATCH"]').setValue(true)
  expect(wrapper.emitted('update:modelValue')).toBeUndefined()
  await wrapper.get('[data-testid="confirm-invoice-selection"]').trigger('click')
  expect(wrapper.emitted('update:modelValue')?.at(-1)).toEqual([[3,1]])
  await wrapper.setProps({supplierName:'无关单位'})
  await wrapper.get('[data-testid="choose-invoices"]').trigger('click')
  expect(wrapper.get('[role="dialog"]').text()).not.toContain('MATCH');expect(wrapper.text()).toContain('EXISTING')
  expect(wrapper.emitted('update:modelValue')).toHaveLength(1)
  wrapper.unmount()
 })
 it('requires a payee and preserves existing links until the user explicitly removes them',async()=>{
  const wrapper=mount(PaymentInvoicePicker,{props:{modelValue:[1],supplierName:'',invoices:[{id:1,invoice_number:'OLD',seller_name:''},{id:2,invoice_number:'UNSELECTED',seller_name:''}]},global})
  await wrapper.get('[data-testid="choose-invoices"]').trigger('click')
  expect(wrapper.text()).not.toContain('UNSELECTED')
  expect(wrapper.get('[role="dialog"]').text()).toContain('请先选择')
  await wrapper.get('[data-testid="cancel-invoice-selection"]').trigger('click')
  await wrapper.get('[aria-label="移除发票 OLD"]').trigger('click')
  expect(wrapper.emitted('update:modelValue')).toEqual([[[]]])
  wrapper.unmount()
 })
 it('keeps choices through searches and discards unconfirmed changes when cancelled',async()=>{
  const wrapper=mount(PaymentInvoicePicker,{props:{modelValue:[],supplierName:'甲公司',invoices:[{id:1,invoice_number:'FIRST',seller_name:'甲公司'},{id:2,invoice_number:'SECOND',seller_name:'甲公司'}]},global})
  await wrapper.get('[data-testid="choose-invoices"]').trigger('click')
  expect(wrapper.findAll('input[type="checkbox"]').every(input=>!(input.element as HTMLInputElement).checked)).toBe(true)
  await wrapper.get('[aria-label="关联发票 FIRST"]').setValue(true)
  await wrapper.get('[aria-label="搜索可关联发票"]').setValue('SECOND')
  expect(wrapper.find('[aria-label="关联发票 FIRST"]').exists()).toBe(false)
  await wrapper.get('[aria-label="关联发票 SECOND"]').setValue(true)
  await wrapper.get('[data-testid="cancel-invoice-selection"]').trigger('click')
  expect(wrapper.emitted('update:modelValue')).toBeUndefined()
  await wrapper.get('[data-testid="choose-invoices"]').trigger('click')
  expect(wrapper.findAll('input[type="checkbox"]').every(input=>!(input.element as HTMLInputElement).checked)).toBe(true)
  await wrapper.get('[aria-label="关联发票 FIRST"]').setValue(true)
  await wrapper.get('[aria-label="搜索可关联发票"]').setValue('SECOND')
  await wrapper.get('[aria-label="关联发票 SECOND"]').setValue(true)
  await wrapper.get('[data-testid="confirm-invoice-selection"]').trigger('click')
  expect(wrapper.emitted('update:modelValue')).toEqual([[[1,2]]])
  wrapper.unmount()
 })
 it('explains that existing invoices do not match instead of claiming the invoice library is empty',async()=>{
  const wrapper=mount(PaymentInvoicePicker,{props:{modelValue:[],supplierName:'收款公司',invoices:[{id:1,invoice_number:'OTHER-001',seller_name:'销售公司',total_amount:100,tax_amount:13}]},global})
  await wrapper.get('[data-testid="choose-invoices"]').trigger('click')
  const dialog=wrapper.get('[role="dialog"]')
  expect(dialog.text()).toContain('暂无销售方名称为')
  expect(dialog.text()).toContain('收款公司')
  expect(dialog.findAll('input[type="checkbox"]')).toHaveLength(0)
  expect(wrapper.emitted('update:modelValue')).toBeUndefined()
  await wrapper.setProps({supplierName:'销售公司'})
  expect(dialog.findAll('input[type="checkbox"]')).toHaveLength(1)
  expect((dialog.get('input[type="checkbox"]').element as HTMLInputElement).checked).toBe(false)
  wrapper.unmount()
 })
 it('loads matching payments, posts selected IDs once, and displays the saved reverse links',async()=>{
  const pay={id:9,pay_number:'PAY-009',payee_supplier_name:'甲公司',current_payment_amount:'30.20',project_name:'公园'}
  mocks.request.mockResolvedValue({code:0,data:{seller_name:'甲公司',matched:[pay],linked:[]}})
  const wrapper=mount(InvoicePaymentLinks,{props:{invoiceId:12},global});await flushPromises()
  expect(wrapper.text()).toContain('PAY-009')
  await wrapper.get('[aria-label="关联付款单 PAY-009"]').setValue(true)
  let resolve:any;mocks.request.mockImplementationOnce(()=>new Promise(r=>resolve=r))
  await wrapper.get('[data-testid="save-payment-links"]').trigger('click')
  await wrapper.get('[data-testid="save-payment-links"]').trigger('click')
  const posts=mocks.request.mock.calls.filter(([,o])=>o?.method==='POST')
  expect(posts).toHaveLength(1);expect(posts[0]?.[0]).toBe('/invoice-links/invoices/12/payments')
  expect(JSON.parse(posts[0]?.[1].body)).toEqual({payment_ids:[9]})
  resolve({code:0,data:{seller_name:'甲公司',matched:[pay],linked:[pay]}});await flushPromises()
  expect(wrapper.get('[aria-label="已关联付款单"]').text()).toContain('PAY-009')
  expect(wrapper.get('a').attributes('href')).toBe('/payments/9')
  expect(wrapper.emitted('changed')).toHaveLength(1)
  wrapper.unmount()
 })
 it('discards a late response after switching invoices and preserves a selection on save failure',async()=>{
  let old:any;mocks.request.mockImplementationOnce(()=>new Promise(r=>old=r))
  const wrapper=mount(InvoicePaymentLinks,{props:{invoiceId:1},global})
  mocks.request.mockResolvedValueOnce({code:0,data:{seller_name:'乙公司',linked:[],matched:[{id:2,pay_number:'NEW'}]}})
  await wrapper.setProps({invoiceId:2});await flushPromises()
  old({code:0,data:{seller_name:'甲公司',linked:[],matched:[{id:1,pay_number:'STALE'}]}});await flushPromises()
  expect(wrapper.text()).toContain('NEW');expect(wrapper.text()).not.toContain('STALE')
  await wrapper.get('[aria-label="关联付款单 NEW"]').setValue(true)
  mocks.request.mockRejectedValueOnce(new Error('保存失败，请重试'))
  await wrapper.get('[data-testid="save-payment-links"]').trigger('click');await flushPromises()
  expect(wrapper.get('[role="alert"]').text()).toContain('保存失败')
  expect((wrapper.get('input').element as HTMLInputElement).checked).toBe(true)
  expect(wrapper.emitted('changed')).toBeUndefined()
  wrapper.unmount()
 })
 it('refreshes associations when returning to a cached invoice after editing a payment',async()=>{
  mocks.request.mockResolvedValueOnce({code:0,data:{seller_name:'甲公司',linked:[],matched:[]}})
  const wrapper=mount({components:{InvoicePaymentLinks},data:()=>({shown:true}),template:'<keep-alive><InvoicePaymentLinks v-if="shown" :invoice-id="12"/></keep-alive>'},{global})
  await flushPromises();await wrapper.setData({shown:false})
  mocks.request.mockResolvedValueOnce({code:0,data:{seller_name:'甲公司',linked:[{id:9,pay_number:'SAVED-ELSEWHERE'}],matched:[]}})
  await wrapper.setData({shown:true});await flushPromises()
  expect(wrapper.text()).toContain('SAVED-ELSEWHERE')
  wrapper.unmount()
 })
})
