// @vitest-environment jsdom
import {mount, flushPromises} from '@vue/test-utils'
import {beforeEach, describe, expect, it, vi} from 'vitest'
import ReceiptPaymentLinks from './ReceiptPaymentLinks.vue'
const mocks = vi.hoisted(() => ({request: vi.fn(), confirm: vi.fn()}))
vi.mock('../../api', () => ({request: mocks.request, query: (values:Record<string,any>) => {
 const params = new URLSearchParams()
 for(const [key,value] of Object.entries(values)) if(value !== '' && value != null) params.set(key,String(value))
 return params.toString()
}}))
vi.mock('element-plus', () => ({ElMessageBox: {confirm: mocks.confirm}}))
const stub = {props: ['disabled','loading'], template: '<button :disabled="disabled || loading"><slot/></button>'}
const linked = {id: 1, pay_number: '已关联付款单', current_payment_amount: '10.00'}
const candidate = {id: 2, pay_number: '待关联付款单', current_payment_amount: '20.00'}
const response = {code: 0, data: {linked: [linked], candidates: [candidate], count: 1}}
function open() {return mount(ReceiptPaymentLinks, {props: {receiptId: 8}, global: {stubs: {'el-button': stub, RouterLink: {template: '<a><slot/></a>'}}}})}
describe('explicit receipt links', () => {
 beforeEach(() => {vi.resetAllMocks(); mocks.request.mockResolvedValue(response); mocks.confirm.mockResolvedValue(true)})
 it('only appends the checked payment after a save click', async () => {
  const wrapper = open(); await flushPromises()
  expect(wrapper.text()).toContain(linked.pay_number)
  expect(wrapper.find('input[type=checkbox]').element).toHaveProperty('checked', false)
  await wrapper.find('input[type=checkbox]').setValue(true)
  expect(mocks.request).toHaveBeenCalledTimes(1)
  await wrapper.find('[data-testid=save-receipt-links]').trigger('click'); await flushPromises()
  expect(mocks.request).toHaveBeenCalledWith('/payment-receipts/8/payments', {method: 'POST', body: JSON.stringify({payment_ids: [2]})})
  wrapper.unmount()
 })
 it('retains checked choices when saving fails', async () => {
  const wrapper = open(); await flushPromises()
  await wrapper.find('input[type=checkbox]').setValue(true)
  mocks.request.mockRejectedValueOnce(new Error('保存失败，请重试'))
  await wrapper.find('[data-testid=save-receipt-links]').trigger('click'); await flushPromises()
  expect(wrapper.find('input[type=checkbox]').element).toHaveProperty('checked', true)
  expect(wrapper.find('[role=alert]').text()).toContain('保存失败')
  wrapper.unmount()
 })
 it('does not let an old request overwrite a newly selected receipt', async () => {
  let resolve:any
  mocks.request.mockImplementationOnce(() => new Promise(r => resolve = r))
  const wrapper = open()
  await wrapper.setProps({receiptId: 9}); await flushPromises()
  resolve({code: 0, data: {linked: [{id: 3, pay_number: '旧回单的关联'}], candidates: [], count: 0}})
  await flushPromises()
  expect(wrapper.text()).not.toContain('旧回单的关联')
  expect(wrapper.text()).toContain(linked.pay_number)
  wrapper.unmount()
 })
 it('opens intelligent recommendations and explains matching evidence without checking any payment', async () => {
  mocks.request.mockResolvedValue({...response,data:{...response.data,match_hint:'已根据单位、金额及日期推荐',candidates:[{...candidate,match_score:85,match_level:'high',match_reasons:['收款单位一致','付款金额一致'],match_conflicts:['付款日期相差 12 天']}]}})
  const wrapper = open(); await flushPromises()
  expect(mocks.request).toHaveBeenCalledWith('/payment-receipts/8/payments?page=1&mode=smart')
  expect(wrapper.get('[data-testid="smart-payment-mode"]').attributes('aria-pressed')).toBe('true')
  expect(wrapper.text()).toContain('高度匹配')
  expect(wrapper.text()).toContain('收款单位一致')
  expect(wrapper.text()).toContain('付款金额一致')
  expect(wrapper.text()).toContain('需核对：付款日期相差 12 天')
  expect(wrapper.text()).toContain('已根据单位、金额及日期推荐')
  expect(wrapper.get('input[type="checkbox"]').element).toHaveProperty('checked',false)
  wrapper.unmount()
 })
 it('resets page and checked choices when changing mode or searching', async () => {
  mocks.request.mockResolvedValue({...response,data:{...response.data,count:45}})
  const wrapper = open(); await flushPromises()
  await wrapper.get('[data-testid="next-payment-page"]').trigger('click'); await flushPromises()
  await wrapper.get('input[type="checkbox"]').setValue(true)
  await wrapper.get('[data-testid="all-payment-mode"]').trigger('click'); await flushPromises()
  expect(mocks.request).toHaveBeenLastCalledWith('/payment-receipts/8/payments?page=1')
  expect(wrapper.get('input[type="checkbox"]').element).toHaveProperty('checked',false)
  await wrapper.get('[data-testid="next-payment-page"]').trigger('click'); await flushPromises()
  await wrapper.get('input[type="checkbox"]').setValue(true)
  await wrapper.get('input[aria-label="搜索待关联付款单"]').setValue('PAY')
  await wrapper.get('form').trigger('submit'); await flushPromises()
  expect(mocks.request).toHaveBeenLastCalledWith('/payment-receipts/8/payments?q=PAY&page=1')
  expect(wrapper.get('input[type="checkbox"]').element).toHaveProperty('checked',false)
  wrapper.unmount()
 })
 it('offers all payments when intelligent recommendations are empty', async () => {
  mocks.request.mockResolvedValue({...response,data:{...response.data,candidates:[],count:0}})
  const wrapper = open(); await flushPromises()
  expect(wrapper.text()).toContain('完善回单信息')
  expect(wrapper.text()).toContain('全部查找')
  await wrapper.get('[data-testid="all-payment-mode"]').trigger('click'); await flushPromises()
  expect(mocks.request).toHaveBeenLastCalledWith('/payment-receipts/8/payments?page=1')
  wrapper.unmount()
 })
 it('reloads the selected mode after saving instead of displaying unrelated POST candidates', async () => {
  const wrapper = open(); await flushPromises()
  await wrapper.get('input[type="checkbox"]').setValue(true)
  mocks.request.mockResolvedValueOnce({...response,data:{linked:[linked,candidate],candidates:[{id:3,pay_number:'无关付款单'}],count:1}})
  mocks.request.mockResolvedValueOnce({...response,data:{linked:[linked,candidate],candidates:[],count:0}})
  await wrapper.get('[data-testid="save-receipt-links"]').trigger('click'); await flushPromises()
  expect(mocks.request).toHaveBeenLastCalledWith('/payment-receipts/8/payments?page=1&mode=smart')
  expect(wrapper.text()).not.toContain('无关付款单')
  expect(wrapper.text()).toContain(linked.pay_number)
  expect(wrapper.emitted('changed')).toHaveLength(1)
  wrapper.unmount()
 })
 it('locks stale candidates after loading fails and allows a successful retry', async () => {
  const wrapper = open(); await flushPromises()
  await wrapper.get('input[type="checkbox"]').setValue(true)
  mocks.request.mockRejectedValueOnce(new Error('加载失败'))
  await wrapper.get('form').trigger('submit'); await flushPromises()
  expect(wrapper.get('[role="alert"]').text()).toContain('加载失败')
  expect(wrapper.get('input[type="checkbox"]').attributes('disabled')).toBeDefined()
  expect(wrapper.get('[data-testid="save-receipt-links"]').attributes('disabled')).toBeDefined()
  await wrapper.get('[data-testid="retry-receipt-payments"]').trigger('click'); await flushPromises()
  expect(wrapper.get('input[type="checkbox"]').attributes('disabled')).toBeUndefined()
  expect(wrapper.get('input[type="checkbox"]').element).toHaveProperty('checked',false)
  wrapper.unmount()
 })
 it('does not repeat an uncertain submission until reloading confirms the associations', async () => {
  const wrapper = open(); await flushPromises()
  await wrapper.get('input[type="checkbox"]').setValue(true)
  mocks.request.mockRejectedValueOnce(Object.assign(new Error('提交结果尚未确认'),{uncertain:true}))
  await wrapper.get('[data-testid="save-receipt-links"]').trigger('click'); await flushPromises()
  expect(wrapper.get('input[type="checkbox"]').element).toHaveProperty('checked',true)
  expect(wrapper.get('[data-testid="save-receipt-links"]').attributes('disabled')).toBeDefined()
  await wrapper.get('[data-testid="save-receipt-links"]').trigger('click'); await flushPromises()
  expect(mocks.request.mock.calls.filter(([,options])=>options?.method==='POST')).toHaveLength(1)
  await wrapper.get('[data-testid="retry-receipt-payments"]').trigger('click'); await flushPromises()
  expect(wrapper.get('input[type="checkbox"]').element).toHaveProperty('checked',false)
  await wrapper.get('input[type="checkbox"]').setValue(true)
  expect(wrapper.get('[data-testid="save-receipt-links"]').attributes('disabled')).toBeUndefined()
  wrapper.unmount()
 })
 it('discards an unlink confirmation after the target receipt changes', async () => {
  let confirm!:Function
  const wrapper = open(); await flushPromises()
  mocks.confirm.mockImplementationOnce(()=>new Promise(resolve=>{confirm=resolve}))
  await wrapper.findAll('button').find(button=>button.text()==='解除关联')!.trigger('click')
  await wrapper.setProps({receiptId:9}); await flushPromises()
  confirm(true); await flushPromises()
  expect(mocks.request.mock.calls.filter(([,options])=>options?.method==='DELETE')).toHaveLength(0)
  wrapper.unmount()
 })
 it('requires verification after the server accepts a write but returns malformed link data', async () => {
  const wrapper = open(); await flushPromises()
  await wrapper.get('input[type="checkbox"]').setValue(true)
  mocks.request.mockResolvedValueOnce({code:0,data:{linked:null,candidates:null}})
  await wrapper.get('[data-testid="save-receipt-links"]').trigger('click'); await flushPromises()
  expect(wrapper.get('[data-testid="save-receipt-links"]').attributes('disabled')).toBeDefined()
  expect(wrapper.text()).toContain('提交结果尚未确认')
  expect(wrapper.text()).toContain(linked.pay_number)
  expect(wrapper.get('input[type="checkbox"]').element).toHaveProperty('checked',true)
  await wrapper.get('[data-testid="retry-receipt-payments"]').trigger('click'); await flushPromises()
  expect(wrapper.get('input[type="checkbox"]').attributes('disabled')).toBeUndefined()
  wrapper.unmount()
 })
 it('keeps all-search mode when refreshing after saving', async () => {
  const wrapper = open(); await flushPromises()
  await wrapper.get('[data-testid="all-payment-mode"]').trigger('click'); await flushPromises()
  await wrapper.get('input[type="checkbox"]').setValue(true)
  await wrapper.get('[data-testid="save-receipt-links"]').trigger('click'); await flushPromises()
  expect(mocks.request).toHaveBeenLastCalledWith('/payment-receipts/8/payments?page=1')
  expect(wrapper.get('[data-testid="all-payment-mode"]').attributes('aria-pressed')).toBe('true')
  wrapper.unmount()
 })
})
