<script setup lang="ts">
import type {Row,Field} from './model'
import {watch,onBeforeUnmount,onDeactivated} from 'vue'
const props=defineProps<{modelValue:boolean;title:string;columns:Field[];rows:Row[];page:number;total:number;display:(row:Row,field:Field)=>any}>()
const emit=defineEmits(['update:modelValue'])
const paperStyle=document.createElement('style');paperStyle.textContent='@page {size:A4 landscape;margin:12mm}'
watch(()=>props.modelValue,visible=>{if(visible)document.head.appendChild(paperStyle);else paperStyle.remove()},{immediate:true});onBeforeUnmount(()=>paperStyle.remove());onDeactivated(()=>paperStyle.remove())
const print=()=>window.print()
</script>
<template><el-dialog :model-value="modelValue" :title="title+' · 表格打印预览'" width="94%" destroy-on-close @update:model-value="emit('update:modelValue',$event)"><div v-if="modelValue" class="core-table-print-sheet"><h2>{{title}}</h2><p>第 {{page}} 页 · 本页 {{rows.length}} 条 · 查询结果共 {{total}} 条</p><table><thead><tr><th v-for="field in columns" :key="field.key">{{field.label}}</th></tr></thead><tbody><tr v-for="row in rows" :key="row.id"><td v-for="field in columns" :key="field.key">{{display(row,field)}}</td></tr></tbody></table></div><template #footer><el-button @click="emit('update:modelValue',false)">关闭</el-button><el-button type="primary" @click="print">打印本页</el-button></template></el-dialog></template>
<style scoped>.core-table-print-sheet{overflow:auto;color:#111;background:white}.core-table-print-sheet h2{text-align:center}table{width:100%;border-collapse:collapse;font-size:12px}th,td{border:1px solid #aaa;padding:6px;white-space:normal;overflow-wrap:anywhere;text-align:left}th{background:#f1f1f1}</style>
<style>@media print{body:has(.core-table-print-sheet) *{visibility:hidden}body:has(.core-table-print-sheet) .core-table-print-sheet,body:has(.core-table-print-sheet) .core-table-print-sheet *{visibility:visible}body:has(.core-table-print-sheet) .el-overlay,body:has(.core-table-print-sheet) .el-overlay-dialog{position:static!important;overflow:visible!important;background:transparent!important}body:has(.core-table-print-sheet) .el-dialog{position:static!important;width:100%!important;margin:0!important;box-shadow:none!important;padding:0!important}body:has(.core-table-print-sheet) .el-dialog__header,body:has(.core-table-print-sheet) .el-dialog__footer{display:none!important}.core-table-print-sheet{position:absolute;left:0;top:0;width:100%;overflow:visible!important}.core-table-print-sheet table{font-size:8pt}.core-table-print-sheet tr{break-inside:avoid}.core-table-print-sheet thead{display:table-header-group}}</style>
