<script setup lang="ts">
import {ref,computed,watch,onBeforeUnmount}from 'vue';import {request,safeUrl}from '../api';import {ElMessageBox}from '../feedback';
const props=withDefaults(defineProps<{modelValue:any[];kind?:string;readonly?:boolean}>(),{kind:'order'});const emit=defineEmits(['update:modelValue','busy','blocked']);
const input=ref<HTMLInputElement>();const camera=ref<HTMLInputElement>();const queue=ref<{id:number;file:File;status:string;error:string}[]>([]);let next=0,disposed=false;
const busy=computed(()=>queue.value.some(x=>x.status==='uploading'||x.status==='queued'));const blocked=computed(()=>queue.value.some(x=>x.status==='failed'));
watch([busy,blocked],()=>{emit('busy',busy.value||blocked.value);emit('blocked',blocked.value)},{immediate:true,flush:'sync'});
const name=(x:any)=>x.original_filename||x.name||x.filename||'附件';const url=(x:any)=>safeUrl(x.preview_url||x.url||x.file_path);
async function upload(item:any){item.status='uploading';item.error='';try{if(item.file.size>10*1024*1024)throw Error('文件不能超过 10 MB');const body=new FormData();body.append('file',item.file);body.append('path',({orders:'order_attachments',payments:'pay_attachments',projects:'project_attachments'} as Record<string,string>)[props.kind]||`${props.kind}_attachments`);const r=await request('/upload/',{method:'POST',body});if(disposed)return;if(!r.data||!safeUrl(r.data.url||r.data.file_path))throw Error('上传结果缺少文件地址');emit('update:modelValue',[...props.modelValue,{...r.data,name:r.data.original_filename||item.file.name}]);queue.value=queue.value.filter(x=>x.id!==item.id)}catch(e){if(disposed)return;item.status='failed';item.error=(e as Error).message}}
async function select(event:Event){const el=event.target as HTMLInputElement;const files=Array.from(el.files||[]);el.value='';for(const file of files)queue.value.push({id:++next,file,status:'queued',error:''});for(const item of queue.value.filter(x=>x.status==='queued')){if(disposed)break;await upload(item)}}
async function remove(index:number){try{await ElMessageBox.confirm('从当前记录移除此附件关联？文件本身不会删除。','移除附件',{type:'warning'});emit('update:modelValue',props.modelValue.filter((_,i)=>i!==index))}catch{}}
onBeforeUnmount(()=>{disposed=true;emit('busy',false);emit('blocked',false)});
</script>
<template><section class="attachment-editor"><div class="toolbar"><strong>附件 · {{modelValue.length}}</strong><m-button v-if="!readonly" :disabled="busy" @click="input?.click()">选择文件</m-button><m-button v-if="!readonly" :disabled="busy" @click="camera?.click()">拍照</m-button><input ref="camera" type="file" accept="image/*" capture="environment" hidden @change="select"><input ref="input" type="file" multiple hidden @change="select"></div><p v-if="!readonly" class="muted">支持图片、PDF 和业务文件，单个文件不超过 10 MB。</p><m-empty v-if="!modelValue.length&&!queue.length" :image-size="45" description="暂无附件"/><div v-for="(file,i) in modelValue" :key="i" class="attachment-row"><m-image v-if="/\.(png|jpe?g|gif|webp)$/i.test(name(file))&&url(file)" :src="url(file)" :preview-src-list="[url(file)]" preview-teleported style="width:48px;height:48px" fit="cover"/><a v-if="url(file)" :href="url(file)" target="_blank" rel="noopener noreferrer">{{name(file)}}</a><span v-else>{{name(file)}}（地址不可用）</span><m-button v-if="!readonly" text type="danger" @click="remove(i)">移除</m-button></div><div v-for="item in queue" :key="item.id" class="attachment-row"><span>{{item.file.name}}</span><m-tag :type="item.status==='failed'?'danger':'info'">{{item.status==='failed'?'上传失败':'上传中'}}</m-tag><span>{{item.error}}</span><template v-if="item.status==='failed'"><m-button :disabled="busy" @click="upload(item)">重试</m-button><m-button :disabled="busy" @click="queue=queue.filter(x=>x.id!==item.id)">移除失败项</m-button></template></div></section></template>
