<script setup lang="ts">
import{ref,onMounted,onBeforeUnmount,onActivated,nextTick}from'vue';import{useRoute}from'vue-router';import{request}from'../api';import * as echarts from'echarts';
const route=useRoute(),busy=ref(false),error=ref(''),overview=ref<any>({}),suppliers=ref<any[]>([]),trendEl=ref<HTMLElement>(),statusEl=ref<HTMLElement>();let charts:echarts.ECharts[]=[];let observer:ResizeObserver;
const money=(v:any)=>Number(v||0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
async function load(){busy.value=true;error.value='';try{const [a,b,c,d,dict]=await Promise.all([request('/dashboard/overview'),request('/dashboard/monthly-trend'),request('/dashboard/payment-status'),request('/dashboard/top-suppliers'),request('/dictionary/options?codes=fkzt')]);overview.value=a.data;suppliers.value=d.data.top_suppliers;await nextTick();charts.forEach(x=>x.dispose());charts=[];
if(trendEl.value){const chart=echarts.init(trendEl.value);charts.push(chart);const months=Array.from(new Set<string>([...b.data.order_trend,...b.data.pay_trend].map((x:any)=>x.month))).sort();chart.setOption({color:['#087f78','#b8cebd'],tooltip:{trigger:'axis'},legend:{bottom:0},grid:{left:65,right:20,top:24,bottom:60},xAxis:{type:'category',data:months},yAxis:{type:'value'},series:[['订单金额','order_trend'],['付款金额','pay_trend']].map(([name,key])=>({name,type:'bar',barMaxWidth:26,data:months.map(m=>b.data[key].find((x:any)=>x.month===m)?.amount||0)}))})}
if(statusEl.value){const chart=echarts.init(statusEl.value);charts.push(chart);chart.setOption({color:['#087f78','#69a99a','#c2d6c6','#e3ba71','#96b8c8'],tooltip:{trigger:'item'},legend:{bottom:0,type:'scroll'},series:[{type:'pie',radius:['45%','68%'],center:['50%','44%'],label:{show:false},data:c.data.status_distribution.map((x:any)=>({name:(dict.data?.fkzt||[]).find((o:any)=>String(o.value)===String(x.status))?.label||x.status,value:x.count}))}]})}
observer?.disconnect();observer=new ResizeObserver(()=>charts.forEach(x=>x.resize()));if(trendEl.value)observer.observe(trendEl.value);if(statusEl.value)observer.observe(statusEl.value)
}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
onMounted(load);let activated=false;onActivated(()=>{if(activated)void load();activated=true});onBeforeUnmount(()=>{observer?.disconnect();charts.forEach(x=>x.dispose())});
</script>
<template><div class="page dashboard"><PageHeader :title="String(route.meta.title||'业务概览')" description="项目进展与资金往来，一目了然。"><el-button :loading="busy" @click="load">刷新数据</el-button></PageHeader><el-alert v-if="error" :title="error" type="error" :closable="false"/><div v-loading="busy" class="stats-grid"><article class="stat-card featured"><span>订单总金额</span><strong>¥ {{money(overview.total_order_amount)}}</strong><small>{{overview.order_count||0}} 笔订单</small></article><article class="stat-card"><span>已付款总额</span><strong>¥ {{money(overview.total_paid_amount)}}</strong><small>{{overview.pay_count||0}} 笔付款</small></article><article class="stat-card"><span>待付款余额</span><strong>¥ {{money(overview.pending_amount)}}</strong><small>订单金额减累计付款</small></article><article class="stat-card"><span>业务往来单位</span><strong>{{overview.supplier_count||0}} <small>家供应商</small></strong><small>{{overview.payer_count||0}} 家付款单位</small></article></div><div class="chart-grid"><section class="panel"><h2>月度资金趋势</h2><div ref="trendEl" class="chart"/></section><section class="panel"><h2>付款状态分布</h2><div ref="statusEl" class="chart"/></section></div><section class="panel"><h2>供应商订单排行</h2><el-table :data="suppliers" empty-text="暂无供应商订单"><el-table-column type="index" label="排名" width="80"/><el-table-column prop="name" label="供应商"/><el-table-column prop="order_count" label="订单数量" width="140"/><el-table-column label="订单金额" align="right" width="200"><template #default="{row}">¥ {{money(row.total_amount)}}</template></el-table-column></el-table></section></div></template>
