import {defineComponent,h,ref,watch,Fragment,inject,provide,useId,type App,type VNode} from 'vue';
import {Button,Popup,Empty,Tag,Image as VanImage,showImagePreview,Loading} from 'vant';

function flatten(nodes:any[]):VNode[]{return nodes.flatMap(n=>n?.type===Fragment?flatten(n.children||[]):typeof n?.type==='symbol'?[]:[n]).filter(Boolean)}
export const Column=defineComponent({name:'MobileColumn',setup:()=>()=>null});
export const Option=defineComponent({name:'MobileOption',setup:()=>()=>null});
export const CardTable=defineComponent({name:'MobileCardTable',inheritAttrs:false,props:{data:{type:Array,default:()=>[]}},emits:['selection-change','row-click','current-change'],setup(p,{slots,emit}){
 const chosen=ref<any[]>([]);watch(()=>p.data,()=>{chosen.value=[];emit('selection-change',[]) });
 const select=(row:any,on:boolean)=>{chosen.value=on?[...chosen.value.filter(x=>x!==row),row]:chosen.value.filter(x=>x!==row);emit('selection-change',chosen.value)};
 return()=>{const expand=(rows:any[]):any[]=>rows.flatMap(row=>[row,...expand(row.children||[])]);const records=expand(p.data);const cols=flatten(slots.default?.()||[]).filter(n=>n.type===Column);const selection=cols.some(c=>c.props?.type==='selection');return h('div',{class:'m-records'},[
 selection&&p.data.length?h('label',{class:'m-select-all'},[h('input',{type:'checkbox',checked:chosen.value.length===records.length,onChange:(e:any)=>{chosen.value=e.target.checked?[...records]:[];emit('selection-change',chosen.value)}}),'选择本页全部']):null,
 ...records.map((row:any,index)=>h('article',{class:'m-record',key:row.id??index,tabindex:0,onClick:(e:any)=>{if(!e.target.closest('button,input,a,select,textarea')){emit('row-click',row);emit('current-change',row)}},onKeydown:(e:any)=>{if(e.key==='Enter'&&e.target===e.currentTarget)emit('row-click',row)}},[
 selection?h('label',{class:'m-select-row'},[h('input',{type:'checkbox',checked:chosen.value.includes(row),onChange:(e:any)=>select(row,e.target.checked)}),`选择第 ${index+1} 条`]):null,
 ...cols.filter(c=>c.props?.type!=='selection').map(c=>h('div',{class:['m-record-field',c.props?.label==='操作'&&'m-record-actions']},[h('span',{class:'m-record-label'},c.props?.label||''),h('div',{class:'m-record-value'},typeof (c.children as any)?.default==='function'?(c.children as any).default({row,$index:index}):String(row[c.props?.prop]??'—'))]))])),
 !p.data.length?h(Empty,{description:'暂无记录'}):null]);};
}});
export const MobileSelect=defineComponent({name:'MobileSelect',inheritAttrs:false,props:{modelValue:null,placeholder:String,disabled:Boolean,multiple:Boolean,clearable:Boolean,allowCreate:Boolean},emits:['update:modelValue','change'],setup(p,{slots,emit,attrs}){
 const open=ref(false),search=ref('');const id=inject<string>('field-id','');
 const commit=(value:any)=>{emit('update:modelValue',value);emit('change',value)};
 return()=>{const options=flatten(slots.default?.()||[]).filter(n=>n.type===Option).map(n=>n.props||{});const selected=(v:any)=>p.multiple?(p.modelValue||[]).includes(v):p.modelValue===v;const choose=(v:any)=>{commit(p.multiple?selected(v)?p.modelValue.filter((x:any)=>x!==v):[...(p.modelValue||[]),v]:v);if(!p.multiple)open.value=false};return h('div',{class:'m-choice'},[
 h('button',{...attrs,id,type:'button',disabled:p.disabled,class:'m-choice-trigger',onClick:()=>{search.value='';open.value=true}},[options.filter(o=>selected(o.value)).map(o=>o.label).join('、')||(p.modelValue&&!p.multiple?String(p.modelValue):p.placeholder||'请选择'),' ▾']),
 h(Popup,{show:open.value,position:'bottom',round:true,style:{maxHeight:'85dvh'},'onUpdate:show':(v:boolean)=>open.value=v},{default:()=>h('section',{class:'m-choice-panel'},[
 h('header',[h('strong',p.placeholder||'选择项目'),h(Button,{size:'small',onClick:()=>open.value=false},()=> '完成')]),
 h('input',{class:'m-control',placeholder:'搜索选项',value:search.value,onInput:(e:any)=>search.value=e.target.value}),
 p.clearable!==undefined&&p.clearable!==false?h(Button,{size:'small',onClick:()=>{commit(p.multiple?[]:null);open.value=false}},()=> '清除选择'):null,
 ...options.filter(o=>String(o.label||'').toLowerCase().includes(search.value.toLowerCase())).map(o=>h('button',{'data-choice':true,type:'button',class:['m-option',selected(o.value)&&'selected'],disabled:o.disabled,onClick:()=>choose(o.value)},`${selected(o.value)?'✓ ':''}${o.label??o.value}`)),
 p.allowCreate!==undefined&&p.allowCreate!==false&&search.value?h(Button,{onClick:()=>choose(search.value)},()=>`使用“${search.value}”`):null
 ])})]);};
}});
const Input=defineComponent({inheritAttrs:false,props:['modelValue','type','disabled','placeholder','min','max','rows'],emits:['update:modelValue','change'],setup(p,{emit,attrs}){const id=inject('field-id','');return()=>h(p.type==='textarea'?'textarea':'input',{...attrs,id,class:['m-control',attrs.class],type:p.type==='textarea'?undefined:p.type||'text',rows:p.rows||3,disabled:p.disabled,placeholder:p.placeholder,min:p.min,max:p.max,value:p.modelValue??'',onInput:(e:any)=>emit('update:modelValue',e.target.value),onChange:(e:any)=>emit('change',e.target.value)})}});
const button=defineComponent({inheritAttrs:false,props:{type:String,loading:Boolean,disabled:Boolean,nativeType:String,link:Boolean,text:Boolean,plain:Boolean,size:String},setup(p,{slots,attrs}){return()=>h(Button,{...attrs,type:['primary','danger','warning','success'].includes(p.type||'')?p.type as 'primary'|'danger'|'warning'|'success':'default',loading:!!p.loading,disabled:!!p.disabled,nativeType:p.nativeType==='submit'?'submit':p.nativeType==='reset'?'reset':'button',plain:!!p.plain,size:p.size==='small'||p.link||p.text?'small':'normal'},slots)}});
const FormItem=defineComponent({props:{label:String,required:Boolean},setup(p,{slots}){const id=useId();provide('field-id',id);return()=>h('div',{class:'m-form-item'},[h('label',{for:id},`${p.label||''}${p.required?' *':''}`),slots.default?.()])}});
const Dialog=defineComponent({inheritAttrs:false,props:['modelValue','title','beforeClose'],emits:['update:modelValue'],setup(p,{emit,slots}){const close=()=>{const done=()=>emit('update:modelValue',false);if(p.beforeClose)p.beforeClose(done);else done()};return()=>h(Popup,{show:!!p.modelValue,position:'bottom',teleport:'body',style:{height:'94dvh',width:'100%'},round:true,closeOnClickOverlay:false},{default:()=>h('section',{class:'m-dialog'},[h('header',[h('h2',p.title),h(Button,{size:'small',onClick:close},()=> '关闭')]),h('div',{class:'m-dialog-body'},slots.default?.()),h('footer',slots.footer?.())])})}});
const groupKey=Symbol('checks');
const CheckboxGroup=defineComponent({props:['modelValue'],emits:['update:modelValue','change'],setup(p,{emit,slots}){provide(groupKey,{values:()=>p.modelValue||[],change:(v:any)=>{emit('update:modelValue',v);emit('change',v)}});return()=>h('div',{class:'m-check-group'},slots.default?.())}});
const Checkbox=defineComponent({props:['modelValue','value','label','disabled'],emits:['update:modelValue','change'],setup(p,{emit,slots}){const group=inject<any>(groupKey,null);return()=>h('label',{class:'m-check'},[h('input',{type:'checkbox',disabled:p.disabled,checked:group?group.values().includes(p.value??p.label):!!p.modelValue,onChange:(e:any)=>{const value=p.value??p.label;if(group)group.change(e.target.checked?[...group.values(),value]:group.values().filter((x:any)=>x!==value));else{emit('update:modelValue',e.target.checked);emit('change',e.target.checked)}}}),slots.default?.()||p.label])}});
const Pagination=defineComponent({props:{currentPage:{default:1},pageSize:{default:20},total:{default:0}},emits:['update:currentPage','change'],setup(p,{emit}){const change=(n:number)=>{emit('update:currentPage',n);emit('change',n)};return()=>h('nav',{class:'m-pagination'},[h(Button,{size:'small',disabled:p.currentPage<=1,onClick:()=>change(p.currentPage-1)},()=> '上一页'),h('span',`${p.currentPage} / ${Math.max(1,Math.ceil(p.total/p.pageSize))} · ${p.total} 条`),h(Button,{size:'small',disabled:p.currentPage*p.pageSize>=p.total,onClick:()=>change(p.currentPage+1)},()=> '下一页')])}});
const Tree=defineComponent({props:['data','defaultCheckedKeys','nodeKey','props'],emits:['check'],setup(p,{emit,expose}){const checked=ref<any[]>(p.defaultCheckedKeys||[]);expose({setCheckedKeys:(v:any[])=>checked.value=[...v],getCheckedKeys:()=>[...checked.value]});function render(nodes:any[],depth=0):any[]{return (nodes||[]).flatMap(n=>{const key=n[p.nodeKey||'id'];return [h('label',{class:'m-check',style:{paddingLeft:`${depth*14}px`}},[h('input',{type:'checkbox',checked:checked.value.includes(key),onChange:(e:any)=>{checked.value=e.target.checked?[...checked.value,key]:checked.value.filter(x=>x!==key);emit('check',n,{checkedKeys:[...checked.value]})}}),n[p.props?.label||'label']]),...render(n[p.props?.children||'children'],depth+1)]})};return()=>h('div',render(p.data))}});
function wrapper(tag:string,cls:string){return defineComponent({setup(_, {slots}){return()=>h(tag,{class:cls},slots.default?.())}})}
const controls:Record<string,any>={Button:button,Input,Select:MobileSelect,Option,Table:CardTable,TableColumn:Column,Form:wrapper('form','m-form'),FormItem,Dialog,Checkbox,CheckboxGroup,Pagination,Tree,
 Card:defineComponent({props:['header'],setup(p,{slots}){return()=>h('section',{class:'panel'},[p.header&&h('h3',p.header),slots.default?.()])}}),
 Statistic:defineComponent({props:['title','value','precision'],setup:p=>()=>h('div',{class:'m-stat'},[h('span',p.title),h('strong',Number(p.value||0).toFixed(p.precision||0))])}),
 Alert:defineComponent({props:['title','type'],setup:p=>()=>h('p',{class:['m-alert',p.type],role:'status'},p.title)}),
 Empty:defineComponent({props:['description'],setup:p=>()=>h(Empty,{description:p.description})}),
 Tag:defineComponent({props:['type'],setup(p,{slots}){return()=>h(Tag,{type:['danger','success','warning'].includes(p.type||'')?p.type:'primary',plain:true},slots)}}),
 Image:defineComponent({props:['src','previewSrcList'],setup:p=>()=>h(VanImage,{src:p.src,fit:'cover',onClick:()=>showImagePreview(p.previewSrcList||[p.src])})}),
 Descriptions:defineComponent({props:['title'],setup(p,{slots}){return()=>h('section',{class:'panel'},[p.title&&h('h3',p.title),slots.default?.()])}}),
 DescriptionsItem:defineComponent({props:['label'],setup(p,{slots}){return()=>h('div',{class:'m-record-field'},[h('span',{class:'m-record-label'},p.label),h('div',{class:'m-record-value'},slots.default?.())])}}),
 Popover:defineComponent({setup(_,{slots}){return()=>h('details',{class:'m-more'},[h('summary','显示字段'),slots.default?.()])}}),
 Result:defineComponent({props:['title','subTitle'],setup(p,{slots}){return()=>h('div',[h(Empty,{description:p.title||p.subTitle}),slots.extra?.()])}}),
 Switch:defineComponent({props:['modelValue','disabled','activeValue','inactiveValue'],emits:['update:modelValue','change'],setup(p,{emit}){return()=>h('input',{type:'checkbox',role:'switch',disabled:p.disabled,checked:p.modelValue===(p.activeValue??true),onChange:(e:any)=>{const v=e.target.checked?(p.activeValue??true):(p.inactiveValue??false);emit('update:modelValue',v);emit('change',v)}})}}),
 InputNumber:defineComponent({props:['modelValue','min','max','disabled'],emits:['update:modelValue','change'],setup(p,{emit}){return()=>h(Input,{...p,type:'number','onUpdate:modelValue':(v:string)=>emit('update:modelValue',v===''?undefined:Number(v)),onChange:(v:string)=>emit('change',Number(v))})}}),
};
for(const [name,type]of [['DatePicker','date'],['TimePicker','time']])controls[name]=defineComponent({props:['modelValue','disabled'],emits:['update:modelValue','change'],setup(p,{emit}){return()=>h(Input,{...p,type,'onUpdate:modelValue':(v:string)=>emit('update:modelValue',v),onChange:(v:string)=>emit('change',v)})}});
export function installControls(app:App){for(const [key,component] of Object.entries(controls))app.component('M'+key,component);app.directive('loading',{mounted(el,b){if(b.value)el.setAttribute('aria-busy','true')},updated(el,b){el.setAttribute('aria-busy',String(!!b.value))}})}
