<script setup lang="ts">
import PageHeader from "../../components/PageHeader.vue";
import { ref,onMounted,computed } from 'vue'
import { ElMessage,ElMessageBox } from '../../feedback'
import { allRows, request } from '../../api'
import {useSystemDraft} from './useSystemDraft'
import type {Row} from './helpers'
const rows=ref<Row[]>([]), details=ref<Row[]>([]), selected=ref<Row>(), search=ref(''), loading=ref(false), busy=ref(false), dialog=ref(false), detailMode=ref(false), form=ref<Row>({})
const baseline=ref('')
const dirty=computed(()=>dialog.value&&JSON.stringify(form.value)!==baseline.value)
const {allowDiscard,beforeClose}=useSystemDraft(dirty,busy,()=>{dialog.value=false})
const fail=(e:unknown)=>ElMessage.error(e instanceof Error?e.message:String(e))
async function load(){loading.value=true;try{rows.value=await allRows('/dictionary/list',{code_desc:search.value});if(selected.value&&!rows.value.some(x=>x.id===selected.value?.id)){selected.value=undefined;details.value=[]}}catch(e){fail(e)}finally{loading.value=false}}
let sequence=0
async function select(row:Row){selected.value=row;details.value=[];const ticket=++sequence;try{const items=await allRows('/dictionary/detail/list',{dic_id:row.id});if(ticket===sequence)details.value=items}catch(e){fail(e)}}
function edit(detail:boolean,row?:Row){detailMode.value=detail;form.value=row?{...row}:{order_no:0};baseline.value=JSON.stringify(form.value);dialog.value=true}
async function save(){if(busy.value)return;const key=detailMode.value?'value':'name';if(!String(form.value.code||'').trim()||!String(form.value[key]||'').trim())return ElMessage.warning('请填写代码和描述');busy.value=true;try{const base=detailMode.value?'/dictionary/detail':'/dictionary';const body={...form.value,...(detailMode.value?{dic_id:selected.value?.id}:{})};await request(base+(form.value.id?'/'+form.value.id:detailMode.value?'':'/'),{method:form.value.id?'PUT':'POST',body:JSON.stringify(body)});dialog.value=false;ElMessage.success('保存成功');if(detailMode.value&&selected.value)await select(selected.value);else await load()}catch(e){fail(e)}finally{busy.value=false}}
async function remove(detail:boolean,row:Row){if(busy.value)return;try{await ElMessageBox.confirm(`确定删除“${row.code}”？`,'删除确认',{type:'warning'});busy.value=true;await request(`${detail?'/dictionary/detail':'/dictionary'}/${row.id}`,{method:'DELETE'});if(detail&&selected.value)await select(selected.value);else{if(selected.value?.id===row.id){selected.value=undefined;details.value=[];++sequence}await load()}ElMessage.success('删除成功')}catch(e){if(e!=='cancel'&&e!=='close')fail(e)}finally{busy.value=false}}
onMounted(load)
</script>
<template><section class="page"><PageHeader title="数据字典" description="选择字典，维护对应代码值和排序。"/><div class="dictionary-grid"><div class="panel"><div class="toolbar"><m-input v-model="search" placeholder="代码 / 描述" clearable @keyup.enter="load"/><m-button @click="load">查询</m-button><m-button type="primary" @click="edit(false)">新增字典</m-button></div><m-table :data="rows" v-loading="loading" highlight-current-row @row-click="select" empty-text="暂无字典"><m-table-column prop="code" label="代码"/><m-table-column prop="name" label="描述"/><m-table-column label="操作" width="135"><template #default="{row}"><m-button link type="primary" @click.stop="edit(false,row)">编辑</m-button><m-button link type="danger" :disabled="busy" @click.stop="remove(false,row)">删除</m-button></template></m-table-column></m-table></div><div class="panel"><div class="toolbar"><h2>{{selected?.name||'字典明细'}}</h2><m-button type="primary" :disabled="!selected" @click="edit(true)">新增明细</m-button></div><m-table :data="details" :empty-text="selected?'暂无明细':'请先选择左侧字典'"><m-table-column prop="code" label="代码"/><m-table-column prop="value" label="代码值"/><m-table-column prop="order_no" label="排序" width="80"/><m-table-column label="操作" width="135"><template #default="{row}"><m-button link type="primary" @click="edit(true,row)">编辑</m-button><m-button link type="danger" :disabled="busy" @click="remove(true,row)">删除</m-button></template></m-table-column></m-table></div></div><m-dialog v-model="dialog" :title="`${form.id?'编辑':'新增'}${detailMode?'明细':'字典'}`" width="500px" :close-on-click-modal="false" :before-close="beforeClose"><m-form label-width="80px"><m-form-item label="代码" required><m-input v-model="form.code"/></m-form-item><m-form-item :label="detailMode?'代码值':'描述'" required><m-input v-if="detailMode" v-model="form.value"/><m-input v-else v-model="form.name"/></m-form-item><m-form-item v-if="detailMode" label="排序"><m-input-number v-model="form.order_no" :precision="0"/></m-form-item></m-form><template #footer><m-button :disabled="busy" @click="allowDiscard">取消</m-button><m-button type="primary" :loading="busy" @click="save">保存</m-button></template></m-dialog></section></template>

