<script setup lang="ts">
import {ref,watch} from 'vue'
import {useRoute} from 'vue-router'
import {request} from '../../api'
import type {Row} from './helpers'
import Payments from './PortalPayments.vue'
const route=useRoute(),data=ref<Row>(),loading=ref(true),error=ref('')
const money=(value:any)=>Number(value||0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2})
let sequence=0
async function load(){const ticket=++sequence;loading.value=true;error.value='';data.value=undefined;try{const result=await request<Row>(`/portal/reconcile/${encodeURIComponent(String(route.params.token))}/data`);if(ticket===sequence)data.value=result.data}catch(e){if(ticket===sequence)error.value=e instanceof Error?e.message:'对账单加载失败'}finally{if(ticket===sequence)loading.value=false}}
watch(()=>route.params.token,load,{immediate:true})
function print(){window.print()}
</script>
<template><main class="portal" v-loading="loading"><header><div><p class="eyebrow">供应商服务 · 财务对账</p><h1>供应商对账单</h1><p v-if="data" class="muted">{{data.supplier?.name}} · 联系人：{{data.supplier?.contact_person||'—'}}</p></div><div class="no-print"><m-button @click="load">刷新</m-button><m-button :disabled="!data" type="primary" @click="print">打印对账单</m-button></div></header><m-result v-if="error" icon="error" title="无法查看对账单" :sub-title="error"><template #extra><m-button @click="load">重试</m-button></template></m-result><template v-if="data"><div class="stats"><div><span>订单总额</span><strong>¥ {{money(data.analysis?.total_orders)}}</strong></div><div><span>已收款总额</span><strong>¥ {{money(data.analysis?.total_received)}}</strong></div><div><span>待结余额</span><strong>¥ {{money(data.analysis?.outstanding_balance)}}</strong></div></div><m-empty v-if="!data.grouped_orders?.length&&!data.unlinked_payments?.length" description="暂无对账记录"/><section v-for="group in data.grouped_orders" :key="group.project_name" class="project"><div class="project-title"><h2>{{group.project_name}}</h2><p>订单 ¥ {{money(group.stats?.total_orders)}}　已收 ¥ {{money(group.stats?.total_paid)}}　余额 ¥ {{money(group.stats?.balance)}}</p></div><article v-for="order in group.orders" :key="order.id" class="order"><div class="order-heading"><div><span class="muted">{{String(order.create_at||'').slice(0,10)}} · {{order.order_number}}</span><h3>{{order.material_name||'订单'}} <small class="muted">{{order.material_details}}</small></h3><p v-if="order.quantity!=null">数量：{{order.quantity}} {{order.material_unit}}<span v-if="order.price!=null">　单价：{{order.price}}</span></p></div><strong class="money">¥ {{money(order.order_amount)}}</strong></div><Payments v-if="order.pays?.length" :rows="order.pays"/><p v-else class="muted">暂无关联收款</p></article></section><section v-if="data.unlinked_payments?.length" class="project"><h2>未关联订单的收款</h2><Payments :rows="data.unlinked_payments"/></section><footer class="muted">此对账单仅展示当前分享链接对应的供应商往来记录。金额如有疑问，请联系业务负责人核对。</footer></template></main></template>
<style scoped>.portal{max-width:1200px;margin:auto;padding:40px 24px;background:#f5f8f7;min-height:100vh}header,.project-title,.order-heading{display:flex;justify-content:space-between;gap:20px;align-items:center}.eyebrow{font-size:13px;letter-spacing:2px;color:#34705c}h1{font-size:32px;margin:8px 0}h2{font-size:20px}h3{font-size:17px}small{font-weight:400}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin:28px 0}.stats>div{background:white;padding:26px;border-radius:12px;border:1px solid #dce7e1}.stats span,.stats strong{display:block}.stats strong{font-size:26px;margin-top:12px;color:#18533e;font-variant-numeric:tabular-nums}.project{background:white;border:1px solid #dce7e1;border-radius:12px;padding:24px;margin-bottom:22px}.project-title{border-bottom:1px solid #e7eeea;margin-bottom:8px}.project-title p{font-size:13px;color:#50665d}.order{padding:18px 0;border-bottom:1px solid #edf1ee}.order:last-child{border-bottom:0}.order-heading>strong{font-size:22px;white-space:nowrap}footer{padding:20px 0;font-size:13px}@media(max-width:700px){header,.project-title{display:block}.stats{grid-template-columns:1fr}.portal{padding:20px 12px}.project{padding:16px}.order-heading{align-items:flex-start}.stats strong{font-size:23px}}@media print{.no-print{display:none}.portal{padding:0;background:white}.project,.order{break-inside:avoid}.stats>div{padding:12px}}</style>

