"""Add attachment table

Revision ID: 562f67c555f3
Revises: 8d4c61cec68d
Create Date: 2026-01-07 02:47:21.700683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '562f67c555f3'
down_revision = '8d4c61cec68d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ums_attachment',
    sa.Column('id', sa.Integer(), nullable=False, comment='自增id'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='项目ID'),
    sa.Column('attachment_code', sa.String(length=64), nullable=False, comment='附件编号'),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='文件名'),
    sa.Column('original_filename', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('file_path', sa.String(length=512), nullable=False, comment='文件路径'),
    sa.Column('file_size', sa.BigInteger(), nullable=False, comment='文件大小（字节）'),
    sa.Column('create_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['project_id'], ['ums_project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ums_attachment')
    # ### end Alembic commands ###
