"""empty message

Revision ID: 688228a1819a
Revises: 562f67c555f3
Create Date: 2026-01-07 03:19:38.128331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '688228a1819a'
down_revision = '562f67c555f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ums_order',
    sa.Column('id', sa.Integer(), nullable=False, comment='自增id'),
    sa.Column('order_number', sa.String(length=64), nullable=False, comment='订单编号'),
    sa.Column('material_name', sa.String(length=128), nullable=False, comment='材料名称'),
    sa.Column('project_name', sa.String(length=128), nullable=True, comment='项目名称'),
    sa.Column('supplier_id', sa.Integer(), nullable=True, comment='供应商ID'),
    sa.Column('contact_phone', sa.String(length=32), nullable=True, comment='联系电话'),
    sa.Column('cutting_time', sa.Date(), nullable=True, comment='下料时间'),
    sa.Column('estimated_arrival_time', sa.Date(), nullable=True, comment='预计到场时间'),
    sa.Column('material_details', sa.Text(), nullable=True, comment='材料明细'),
    sa.Column('order_amount', sa.Numeric(precision=18, scale=2), nullable=True, comment='订单金额'),
    sa.Column('material_manager', sa.String(length=64), nullable=True, comment='材料负责人'),
    sa.Column('sub_project_manager', sa.String(length=64), nullable=True, comment='分项目负责人'),
    sa.Column('create_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['supplier_id'], ['ums_supplier.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ums_order')
    # ### end Alembic commands ###
