"""add supplier_id to material_planning

Revision ID: 8be4c914f107
Revises: ebe029624e8a
Create Date: 2026-01-26 23:51:10.524783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8be4c914f107'
down_revision = 'ebe029624e8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material_planning', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_id', sa.Integer(), nullable=True, comment='拟定供应商ID'))
        batch_op.create_foreign_key('fk_material_planning_supplier_id_ums_supplier', 'ums_supplier', ['supplier_id'], ['id'])

    with op.batch_alter_table('nursery_transaction', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('ums_pay', schema=None) as batch_op:
        # Avoid dropping without name if possible, or just skip if it's unrelated noise
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.create_foreign_key(None, 'ums_payer', ['payer_supplier_id'], ['id'], ondelete='SET NULL')
        pass

    with op.batch_alter_table('ums_rights', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('ums_user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=102),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ums_user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=102),
               existing_nullable=False)

    with op.batch_alter_table('ums_rights', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)

    with op.batch_alter_table('ums_pay', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'ums_supplier', ['payer_supplier_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('nursery_transaction', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('material_planning', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('supplier_id')

    # ### end Alembic commands ###
