"""empty message

Revision ID: 8d4c61cec68d
Revises: 
Create Date: 2026-01-07 01:56:04.615424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d4c61cec68d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ums_project',
    sa.Column('id', sa.Integer(), nullable=False, comment='自增id'),
    sa.Column('project_name', sa.String(length=128), nullable=False, comment='项目名称'),
    sa.Column('project_full_name', sa.String(length=256), nullable=True, comment='项目全称'),
    sa.Column('project_scale', sa.String(length=128), nullable=True, comment='项目规模'),
    sa.Column('start_date', sa.Date(), nullable=True, comment='开始日期'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='结束日期'),
    sa.Column('project_status', sa.String(length=32), nullable=True, comment='项目状态'),
    sa.Column('project_amount', sa.Numeric(precision=18, scale=2), nullable=True, comment='项目金额'),
    sa.Column('attachments', sa.Text(), nullable=True, comment='附件'),
    sa.Column('create_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ums_project')
    # ### end Alembic commands ###
