"""empty message

Revision ID: ebe029624e8a
Revises: f9ba26f5b104
Create Date: 2026-01-08 15:56:06.844675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebe029624e8a'
down_revision = 'f9ba26f5b104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ums_pay',
    sa.Column('id', sa.Integer(), nullable=False, comment='自增id'),
    sa.Column('pay_number', sa.String(length=64), nullable=False, comment='付款单编号'),
    sa.Column('order_id', sa.Integer(), nullable=True, comment='关联订单ID'),
    sa.Column('payer_supplier_id', sa.Integer(), nullable=True, comment='付款单位（关联供应商ID）'),
    sa.Column('payee_supplier_id', sa.Integer(), nullable=True, comment='收款单位（关联供应商ID）'),
    sa.Column('payment_purpose', sa.Text(), nullable=True, comment='付款用途'),
    sa.Column('current_payment_amount', sa.Numeric(precision=18, scale=2), nullable=True, comment='本次付款金额'),
    sa.Column('invoice_amount', sa.Numeric(precision=18, scale=2), nullable=True, comment='开票金额'),
    sa.Column('payment_status', sa.String(length=32), nullable=True, comment='付款状态'),
    sa.Column('handler', sa.String(length=64), nullable=True, comment='经办人'),
    sa.Column('create_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['order_id'], ['ums_order.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payee_supplier_id'], ['ums_supplier.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payer_supplier_id'], ['ums_supplier.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pay_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ums_pay')
    # ### end Alembic commands ###
