"""Add OCR fields to material_invoice

Revision ID: f3e0d709c462
Revises: 8be4c914f107
Create Date: 2026-01-27 23:03:43.123972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3e0d709c462'
down_revision = '8be4c914f107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material_invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True, comment='关联项目ID'))
        batch_op.add_column(sa.Column('supplier_id', sa.Integer(), nullable=True, comment='关联供应商ID'))
        batch_op.add_column(sa.Column('invoice_code', sa.String(length=64), nullable=True, comment='发票代码'))
        batch_op.add_column(sa.Column('buyer_tax_num', sa.String(length=64), nullable=True, comment='购买方税号'))
        batch_op.add_column(sa.Column('seller_tax_num', sa.String(length=64), nullable=True, comment='销售方税号'))
        batch_op.add_column(sa.Column('amount_in_words', sa.String(length=128), nullable=True, comment='价税合计(大写)'))
        batch_op.add_column(sa.Column('file_path', sa.String(length=500), nullable=True, comment='文件存储路径'))
        batch_op.add_column(sa.Column('file_name', sa.String(length=200), nullable=True, comment='原始文件名'))
        batch_op.add_column(sa.Column('file_type', sa.String(length=20), nullable=True, comment='文件类型(pdf/jpg/png)'))
        batch_op.add_column(sa.Column('ocr_status', sa.String(length=20), nullable=True, comment='OCR状态: pending/processing/completed/failed'))
        batch_op.add_column(sa.Column('ocr_result', sa.Text(), nullable=True, comment='OCR原始结果JSON'))
        batch_op.add_column(sa.Column('ocr_error', sa.Text(), nullable=True, comment='OCR错误信息'))
        batch_op.add_column(sa.Column('update_at', sa.DateTime(), nullable=True, comment='更新时间'))
        batch_op.alter_column('invoice_number',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.create_foreign_key(None, 'ums_project', ['project_id'], ['id'])
        batch_op.create_foreign_key(None, 'ums_supplier', ['supplier_id'], ['id'])

    with op.batch_alter_table('ums_pay', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'ums_payer', ['payer_supplier_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ums_pay', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'ums_supplier', ['payer_supplier_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('material_invoice', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('invoice_number',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.drop_column('update_at')
        batch_op.drop_column('ocr_error')
        batch_op.drop_column('ocr_result')
        batch_op.drop_column('ocr_status')
        batch_op.drop_column('file_type')
        batch_op.drop_column('file_name')
        batch_op.drop_column('file_path')
        batch_op.drop_column('amount_in_words')
        batch_op.drop_column('seller_tax_num')
        batch_op.drop_column('buyer_tax_num')
        batch_op.drop_column('invoice_code')
        batch_op.drop_column('supplier_id')
        batch_op.drop_column('project_id')

    # ### end Alembic commands ###
