"""Add attachments field to order table

Revision ID: f9ba26f5b104
Revises: 688228a1819a
Create Date: 2026-01-07 03:29:03.739593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9ba26f5b104'
down_revision = '688228a1819a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ums_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachments', sa.Text(), nullable=True, comment='附件'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ums_order', schema=None) as batch_op:
        batch_op.drop_column('attachments')

    # ### end Alembic commands ###
