<script setup lang="ts">
import PageHeader from "../../components/PageHeader.vue";
import {computed,ref,watch} from 'vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import {request,allRows} from '../../api'
import Fields from './Fields.vue'
import {useCacheRefresh} from './useCacheRefresh'
import {useDraftGuard} from './useDraftGuard'
import {exportWorkbook} from './workbook'
import {labels,displayValue,materialColumns,numeric,planPayload,inventoryEdit,type Row} from './domain'
import {invoiceAmounts} from '../core/model'
const props=defineProps<{view:string}>();const entity=computed(()=>props.view==='outbound_records'?'outbound':props.view)
const rows=ref<Row[]>([]),selected=ref<Row[]>([]),busy=ref(false),loading=ref(false),search=ref(''),project=ref<any>(''),status=ref('pending'),remaining=ref(''),stats=ref<Row>({}),options=ref<Record<string,Row[]>>({}),dialog=ref(''),form=ref<Row>({}),fields=ref<string[]>([]),items=ref<Row[]>([]),file=ref<File>(),page=ref(1)
const inventoryField=ref('seller_quantity');const draftBaseline=ref('');const draft=()=>JSON.stringify({form:form.value,items:items.value});watch(dialog,()=>{draftBaseline.value=draft()},{flush:'sync'});const allowDiscard=useDraftGuard(computed(()=>busy.value||(!!dialog.value&&draft()!==draftBaseline.value)),busy);async function closeEditor(){if(busy.value)return;if(await allowDiscard())dialog.value=''};async function beforeClose(done:()=>void){if(busy.value)return;if(await allowDiscard())done()}
const open=computed({get:()=>!!dialog.value,set:(v)=>{if(!v)dialog.value=''}});const titles:Record<string,string>={dashboard:'材料看板',planning:'材料策划',inbound:'材料入库',inventory:'材料库存',outbound:'拟出库计划',outbound_records:'出库记录'};const filtered=computed(()=>rows.value.filter(r=>!search.value||Object.values(r).some(v=>String(v??'').toLowerCase().includes(search.value.toLowerCase()))));const columns=computed(()=>materialColumns[entity.value]||[])
const pageRows=computed(()=>filtered.value.slice((page.value-1)*30,page.value*30))
const base=()=>`/material/${entity.value}`;const ids=()=>selected.value.map(x=>x.id)
function fail(e:any){ElMessage.error(e.message||String(e))}
async function load(preserve:any=false){loading.value=true;if(preserve!==true)selected.value=[];try{if(props.view==='dashboard'){stats.value=(await request<Row>('/material/dashboard/stats')).data;return}rows.value=await allRows(base(),{project_id:project.value,status:props.view==='outbound_records'?'completed':status.value,remaining_status:remaining.value});if(preserve!==true)page.value=1}catch(e){fail(e)}finally{loading.value=false}}
async function init(preserve=false){try{const o=(await request<Row>('/material/options')).data;options.value={...options.value,project_id:o.projects,supplier_id:o.suppliers};await load(preserve)}catch(e){fail(e)}}
watch(()=>props.view,()=>{project.value='';status.value='pending';search.value='';init()},{immediate:true})
async function mutate(path:string,method:string,payload?:any){if(busy.value)return;busy.value=true;try{const result=await request(path,{method,body:payload===undefined?undefined:JSON.stringify(payload)});ElMessage.success(result.msg||'操作成功');dialog.value='';await load()}catch(e){fail(e)}finally{busy.value=false}}
useCacheRefresh(()=>init(true))
const common=['project_id','material_name','material_spec','material_unit','supplier_id']
function edit(row?:Row){inventoryField.value='seller_quantity';form.value=row?{...row,tax_rate:entity.value==='inventory'?String(Number(row.tax_rate||0)*100):row.tax_rate}:{project_id:project.value||null,supplier_id:null};fields.value=entity.value==='planning'?[...common,'planned_total_quantity','planned_price','batch_number']:entity.value==='inventory'?['current_stock','seller_price','seller_quantity','profit_ratio','tax_rate','tax_amount','price_no_tax']:[...common,'batch_number','batch_sub_number','inbound_quantity','inbound_price'];dialog.value='edit'}
async function save(){if(busy.value)return;try{if(['planning','inbound'].includes(entity.value)&&!form.value.project_id)throw Error('请选择项目');if(!form.value.material_name && entity.value!=='inventory')throw Error('请输入材料名称');let payload:Row={...form.value};if(entity.value==='planning')payload=planPayload(payload);if(entity.value==='inbound'){numeric(payload.inbound_quantity,'入库量',true);numeric(payload.inbound_price,'单价')}if(entity.value==='inventory'){if(busy.value)return;busy.value=true;try{const current=(await request<Row>(base()+'/'+payload.id)).data;payload={id:payload.id,...inventoryEdit(inventoryField.value,form.value[inventoryField.value],current)}}finally{busy.value=false}}await mutate(base()+(payload.id?`/${payload.id}`:''),payload.id?'PUT':'POST',payload)}catch(e){fail(e)}}
async function batch(action:string){if(!ids().length){ElMessage.warning('请先选择记录');return}if(action==='supplier'){form.value={supplier_id:null};fields.value=['supplier_id'];dialog.value='supplier';return}if(action==='invoice'){try{const invoice=await allRows('/material/invoice');options.value.invoice_id=invoice.map(r=>{const amounts=invoiceAmounts(r);return {...r,name:`${r.invoice_number||'未编号'} · ${r.seller_name||''} · 价税合计 ${amounts.total} · 不含税金额 ${amounts.untaxed} · 税额 ${amounts.tax}`}});form.value={invoice_id:null};fields.value=['invoice_id'];dialog.value='invoice'}catch(e){fail(e)}return}if(action==='generate'){items.value=selected.value.map(r=>({...r,quantity:r.planned_remaining_quantity}));dialog.value='generate';return}if(action==='outbound'){items.value=selected.value.map(r=>({...r,inventory_id:r.id}));form.value={direct_confirm:false,recipient:'',remark:''};dialog.value='outbound';return}try{await ElMessageBox.confirm(action==='delete'?'删除所选记录？关联的数量调整由服务端执行。':'确认对所选记录执行操作？','确认',{type:'warning'});const path=action==='delete'?(entity.value==='planning'?'/planning/batch':'/inbound/batch-delete'):`/${entity.value}/${action==='confirm'?'batch_confirm':'batch_calculate'}`;await mutate('/material'+path,action==='delete'&&entity.value==='planning'?'DELETE':'POST',{ids:ids()})}catch(e:any){if(e!=='cancel'&&e!=='close')fail(e)}}
async function submitBatch(){try{if(dialog.value==='supplier'){if(!form.value.supplier_id)throw Error('请选择供应商');await mutate(base()+'/batch_supplier','PUT',{ids:ids(),supplier_id:form.value.supplier_id})}else if(dialog.value==='invoice')await mutate(base()+'/batch-invoice','PUT',{ids:ids(),invoice_id:form.value.invoice_id||null});else if(dialog.value==='generate'){for(const i of items.value)numeric(i.quantity,'入库量',true);await mutate('/material/planning/generate_inbound','POST',{items:items.value.map(i=>({id:i.id,quantity:i.quantity}))})}else if(dialog.value==='outbound'){for(const i of items.value)numeric(i.seller_quantity,'销售数量',true);await mutate('/material/outbound/batch','POST',{...form.value,items:items.value.map(i=>({inventory_id:i.id}))})}else if(dialog.value==='single'){if(!form.value.inventory_id)throw Error('请选择库存');numeric(form.value.outbound_quantity,'出库量',true);await mutate('/material/outbound','POST',form.value)}else if(dialog.value==='batchNumber')await mutate(`/material/inbound/${form.value.id}/batch`,'PUT',{batch_number:form.value.batch_number})}catch(e){fail(e)}}
async function remove(row:Row){try{await ElMessageBox.confirm('确认删除该记录？','删除',{type:'warning'});await mutate(`${base()}/${row.id}`,'DELETE')}catch(e:any){if(e!=='cancel'&&e!=='close')fail(e)}}
async function importFile(){if(busy.value)return;if(!file.value||!project.value){ElMessage.warning('请先选择项目和 Excel 文件');return}busy.value=true;try{const data=new FormData();data.append('file',file.value);data.append('project_id',String(project.value));const r=await request('/material/planning/import',{method:'POST',body:data});ElMessage.success(r.msg||'导入成功');dialog.value=''}catch(e){fail(e)}finally{file.value=undefined;await load();busy.value=false}}
async function newOutbound(){try{const stock=await allRows('/material/inventory',{project_id:project.value});options.value.inventory_id=stock.map(r=>({...r,name:`${r.material_name} ${r.material_spec||''} · 库存 ${r.current_stock}`}));form.value={inventory_id:null,outbound_quantity:''};fields.value=['inventory_id','outbound_quantity'];dialog.value='single'}catch(e){fail(e)}}
async function exportRows(){try{await exportWorkbook(filtered.value.map(r=>Object.fromEntries(columns.value.map(c=>[labels[c]||c,r[c]]))),'材料台账.xlsx')}catch(e){fail(e)}}
function single(row:Row){form.value={inventory_id:row.id,outbound_quantity:row.seller_quantity||'1'};fields.value=['outbound_quantity'];dialog.value='single'}
</script>
<template><section class="page"><PageHeader :title="titles[view]" description="按项目管理材料计划、入出库与库存记录。"/>
<div v-if="view==='dashboard'" class="form-grid"><el-card v-for="(label,key) in {total_inventory_value:'库存总值',pending_inbound_count:'待入库',pending_outbound_count:'待出库'}" :key="key"><el-statistic :title="label" :value="Number(stats[key]||0)" :precision="key==='total_inventory_value'?2:0"/></el-card><router-link v-for="v in ['planning','inbound','inventory','outbound']" :key="v" :to="'/material/'+v">{{titles[v]}}</router-link></div>
<template v-else><div class="toolbar"><el-select v-model="project" placeholder="全部项目" clearable filterable @change="load"><el-option v-for="p in options.project_id" :key="p.id" :label="p.name" :value="p.id"/></el-select><el-select v-if="view==='inbound'" v-model="status" @change="load"><el-option label="待入库" value="pending"/><el-option label="已入库" value="completed"/><el-option label="全部" value=""/></el-select><el-select v-if="view==='planning'" v-model="remaining" placeholder="全部余量" clearable @change="load"><el-option v-for="v in ['>0','=0','<0']" :key="v" :label="v" :value="v"/></el-select><el-input v-model="search" placeholder="搜索当前项目的全部记录" clearable/><el-button @click="load">刷新</el-button></div>
<div class="toolbar"><el-button @click="exportRows">导出 Excel</el-button><el-button v-if="view==='outbound'" type="primary" @click="newOutbound">新增出库计划</el-button><el-button v-if="['planning','inbound'].includes(view)" type="primary" @click="edit()">新增</el-button><el-button v-if="view==='planning'" @click="dialog='import'">Excel 导入</el-button><el-button v-if="view==='planning'" @click="batch('generate')">生成入库计划</el-button><el-button v-if="['planning','inventory'].includes(view)" @click="batch('supplier')">{{view==='inventory'?'批量销售商':'批量供应商'}}</el-button><el-button v-if="['inbound','outbound','outbound_records'].includes(view)" @click="batch('invoice')">关联 / 取消发票</el-button><el-button v-if="['inbound','outbound'].includes(view)" :disabled="busy" @click="batch('confirm')">确认{{view==='inbound'?'入库':'出库'}}</el-button><el-button v-if="['planning','inbound'].includes(view)" type="danger" plain :disabled="busy" @click="batch('delete')">批量删除</el-button><el-button v-if="view==='inventory'" @click="batch('calculate')">计算销售信息</el-button><el-button v-if="view==='inventory'" type="primary" @click="batch('outbound')">批量出库</el-button><span class="muted">已选 {{selected.length}} 条</span></div>
<el-table v-loading="loading" :data="pageRows" row-key="id" border @selection-change="selected=$event"><el-table-column type="selection" width="45"/><el-table-column v-for="c in columns" :key="c" :prop="c" :label="labels[c]||c" min-width="125" sortable><template #default="{row}">{{displayValue(c,row[c],entity)}}</template></el-table-column><el-table-column label="操作" fixed="right" width="210"><template #default="{row}"><el-button v-if="view==='inventory'||(view==='inbound'&&row.status==='pending')" link type="primary" @click="edit(row)">编辑</el-button><el-button v-if="view==='inventory'" link type="primary" @click="single(row)">单项出库</el-button><el-button v-if="view==='inbound'" link @click="form={...row};fields=['batch_number'];dialog='batchNumber'">批次</el-button><el-button v-if="view==='planning'||(['inbound','outbound'].includes(view)&&row.status==='pending')" link type="danger" :disabled="busy" @click="remove(row)">删除</el-button><router-link v-if="row.invoice_id" to="/material/invoice">发票库</router-link></template></el-table-column></el-table><el-pagination v-model:current-page="page" :page-size="30" :total="filtered.length" layout="total,prev,pager,next"/></template>
<el-dialog v-model="open" :title="({edit:'编辑材料',supplier:'批量供应商',invoice:'关联发票（留空可取消关联）',generate:'生成入库计划',outbound:'批量出库',single:'单项出库',batchNumber:'修改批次',import:'导入材料策划'} as any)[dialog]" width="850px" :close-on-click-modal="false" :before-close="beforeClose"><template v-if="dialog==='import'"><p>先在页面选择项目；上传策划 Excel 文件。表头：材料名称、规格型号、单位、策划总数、策划单价。</p><a href="/static/templates/material_planning_template.xlsx" download>下载导入模板</a><input type="file" accept=".xlsx,.xls" @change="file=($event.target as HTMLInputElement).files?.[0]"/></template><template v-else-if="dialog==='generate'"><el-table :data="items"><el-table-column prop="material_name" label="材料"/><el-table-column prop="planned_remaining_quantity" label="策划余量"/><el-table-column label="本次入库数量"><template #default="{row}"><el-input v-model="row.quantity"/></template></el-table-column></el-table></template><template v-else-if="dialog==='outbound'"><el-alert title="按库存台账已保存的销售数量生成。需要修改数量时请先编辑台账。" :closable="false"/><el-table :data="items"><el-table-column prop="material_name" label="材料"/><el-table-column prop="current_stock" label="库存"/><el-table-column prop="seller_quantity" label="出库数量"/></el-table><el-checkbox v-model="form.direct_confirm">直接确认出库并扣减库存</el-checkbox><Fields :model="form" :fields="['recipient','remark']"/></template><template v-else-if="dialog==='edit'&&view==='inventory'"><el-alert title="每次修改一个字段。库存与销售数量保持合计不变；利润系数、销售单价及税率会自动重算税额。" :closable="false"/><el-select v-model="inventoryField"><el-option v-for="f in fields" :key="f" :value="f" :label="f==='tax_rate'?'税率（百分比，例如13）':labels[f]"/></el-select><Fields :model="form" :fields="[inventoryField]"/><p v-if="inventoryField==='tax_rate'">输入 13 表示 13%。</p></template><Fields v-else :model="form" :fields="fields" :options="options"/><template #footer><el-button @click="closeEditor">取消</el-button><el-button type="primary" :loading="busy" @click="dialog==='edit'?save():dialog==='import'?importFile():submitBatch()">提交</el-button></template></el-dialog>
</section></template>









