<script setup lang="ts">
import PageHeader from "../../components/PageHeader.vue";
import {computed,ref,watch} from 'vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import {request,allRows} from '../../api'
import Fields from './Fields.vue'
import {useCacheRefresh} from './useCacheRefresh'
import {useDraftGuard} from './useDraftGuard'
import {readNurseryWorkbook,exportWorkbook} from './workbook'
import {labels,displayValue,numeric,outboundItems,settingsValue,type Row} from './domain'
const props=defineProps<{view:string}>(),rows=ref<Row[]>([]),stock=ref<Row[]>([]),stats=ref<Row>({}),busy=ref(false),loading=ref(false),search=ref(''),type=ref(''),page=ref(1),dialog=ref(''),form=ref<Row>({}),items=ref<Row[]>([]),fields=ref<string[]>([]),settings=ref<Row>({category:[],location:[],'non-inventory':[]}),settingType=ref('category'),settingIndex=ref(-1)
const importRows=ref<Row[]>([]);const importRunning=ref(false);const draftBaseline=ref(''),outboundBaseline=ref('');const draft=()=>JSON.stringify({form:form.value,items:items.value});watch(dialog,()=>{draftBaseline.value=draft()},{flush:'sync'});const allowDiscard=useDraftGuard(computed(()=>busy.value||((props.view==='outbound'&&draft()!==outboundBaseline.value)||(!!dialog.value&&dialog.value!=='detail'&&draft()!==draftBaseline.value))),busy);async function closeEditor(){if(busy.value)return;if(await allowDiscard())dialog.value=''};async function beforeClose(done:()=>void){if(busy.value)return;if(await allowDiscard())done()}
const open=computed({get:()=>!!dialog.value,set:(v)=>{if(!v)dialog.value=''}})
const inboundFields=['name','category','spec','unit','quantity','price','location','operator','date','remark'],baseFields=['operator','destination','date','remark']
const options=computed(()=>({category:settings.value.category.map((name:string)=>({name})),location:settings.value.location.map((name:string)=>({name}))}))
const filtered=computed(()=>rows.value.filter(r=>(!type.value||r.type===type.value)&&(!search.value||Object.values(r).some(v=>String(v??'').toLowerCase().includes(search.value.toLowerCase())))))
const columns=computed(()=>props.view==='inventory'?['name','category','spec','unit','quantity','price','location','remark']:props.view==='orders'?['order_no','create_at','operator','destination','item_count','total']:['order_no','type','plant_name','spec','unit','quantity','price','total_price','operator','location','destination','create_at','remark'])
const pageRows=computed(()=>filtered.value.slice((page.value-1)*30,page.value*30))
function fail(e:any){ElMessage.error(e.message||String(e))}
function readSettings(){try{settings.value=settingsValue(localStorage.getItem('nursery_settings'))}catch(e){fail(new Error('本机苗圃设置无法解析，请检查原设置；不会覆盖原数据'))}}
async function load(preserve:any=false){loading.value=true;try{if(props.view==='settings'){readSettings();return}if(props.view==='dashboard'){stats.value=(await request<Row>('/nursery/dashboard/stats')).data;rows.value=stats.value.recent_activities||[];return}if(props.view==='outbound'){stock.value=(await request<Row[]>('/nursery/inventory?all=1')).data;for(const item of items.value){if(!item.is_non_inventory)item.available=stock.value.find(r=>r.id===item.plant_id)?.quantity??'0'}return}if(props.view==='inbound')rows.value=await allRows('/nursery/transactions',{type:'in'});else if(props.view==='orders')rows.value=(await request<Row[]>('/nursery/orders')).data;else rows.value=await allRows(`/nursery/${props.view==='inventory'?'inventory':'transactions'}`);if(preserve!==true)page.value=1}catch(e){fail(e)}finally{loading.value=false}}
useCacheRefresh(async()=>{readSettings();await load(true)})
function newInbound(){form.value={name:'',category:'',spec:'',unit:'株',quantity:'',price:'0',location:'',operator:'Admin',date:new Date().toLocaleDateString('en-CA'),remark:''};fields.value=inboundFields;dialog.value='inbound'}
watch(()=>props.view,()=>{search.value='';type.value='';readSettings();form.value={operator:'Admin',destination:'',date:new Date().toLocaleDateString('en-CA'),remark:''};items.value=[];outboundBaseline.value=draft();load()},{immediate:true})
async function mutate(path:string,method:string,payload?:Row){if(busy.value)return;busy.value=true;try{const result:any=await request(path,{method,body:payload?JSON.stringify(payload):undefined});if(result.success===false)throw Error(result.msg||'操作失败');ElMessage.success(result.msg||'操作成功');dialog.value='';if(props.view==='outbound'){items.value=[];outboundBaseline.value=draft()}await load()}catch(e){fail(e)}finally{busy.value=false}}
function addStock(id:any){const r=stock.value.find(x=>x.id===id);if(r)items.value.push({plant_id:r.id,name:r.name,spec:r.spec,unit:r.unit,quantity:'1',price:String(r.price||'0'),available:r.quantity,is_non_inventory:false})}
function addNonInventory(p?:Row){items.value.push({name:p?.name||'',spec:'-',unit:p?.unit||'株',quantity:'1',price:String(p?.guide_price||'0'),is_non_inventory:true})}
async function save(){try{if(dialog.value==='setting'){const list=[...settings.value[settingType.value]];if(!form.value.name?.trim())throw Error('请输入名称');const value=settingType.value==='non-inventory'?{...form.value,guide_price:numeric(form.value.guide_price,'指导价')}:form.value.name.trim();if(list.some((x:any,i:number)=>i!==settingIndex.value&&(typeof x==='string'?x:x.name)===form.value.name.trim()))throw Error('名称已存在');if(settingIndex.value<0)list.push(value);else list[settingIndex.value]=value;const updated={...settings.value,[settingType.value]:list};localStorage.setItem('nursery_settings',JSON.stringify(updated));settings.value=updated;dialog.value='';return}if(dialog.value==='inbound'){if(!form.value.name)throw Error('请输入苗木名称');numeric(form.value.quantity,'数量',true);numeric(form.value.price,'价格');await mutate('/nursery/inbound','POST',form.value)}else if(dialog.value==='order'){for(const i of items.value){numeric(i.quantity,'数量',true);numeric(i.price,'单价')}await mutate(`/nursery/order/${encodeURIComponent(form.value.order_no)}`,'PUT',{...form.value,items:items.value.map(i=>({id:i.id,quantity:i.quantity,price:i.price}))})}else if(dialog.value==='log'){numeric(form.value.quantity,'数量',true);numeric(form.value.price,'单价');await mutate(`/nursery/transaction/${form.value.id}`,'PUT',form.value)}}catch(e){fail(e)}}
async function submitOutbound(){try{const payload={...form.value,items:outboundItems(items.value)};await ElMessageBox.confirm('确认出库并扣减所选库存？','确认出库');await mutate('/nursery/outbound','POST',payload)}catch(e:any){if(e!=='cancel'&&e!=='close')fail(e)}}
function editOrder(row:Row){form.value={...row,remark:row.items?.[0]?.remark||'',date:row.create_at?.slice(0,10)};items.value=(row.items||[]).map((x:Row)=>({...x}));fields.value=baseFields;dialog.value='order'}
function editLog(row:Row){form.value={...row};fields.value=['plant_name','spec','unit','quantity','price','operator','destination','location','remark'];dialog.value='log'}
async function remove(row:Row){try{await ElMessageBox.confirm(props.view==='orders'?'删除整张出库单并退回库存？':'删除此条流水不会调整库存，确认删除？','确认删除',{type:'warning'});await mutate(props.view==='orders'?`/nursery/order/${encodeURIComponent(row.order_no)}`:`/nursery/transaction/${row.id}`,'DELETE')}catch(e:any){if(e!=='cancel'&&e!=='close')fail(e)}}
function settingEdit(t:string,index=-1){settingType.value=t;settingIndex.value=index;const v=settings.value[t][index];form.value=typeof v==='string'?{name:v}:v?{...v}:{name:'',unit:'株',guide_price:'0'};fields.value=t==='non-inventory'?['name','unit','guide_price']:['name'];dialog.value='setting'}
async function settingDelete(t:string,index:number){try{await ElMessageBox.confirm('删除此设置项？','确认');const updated={...settings.value,[t]:settings.value[t].filter((_:any,i:number)=>i!==index)};localStorage.setItem('nursery_settings',JSON.stringify(updated));settings.value=updated}catch(e:any){if(e!=='cancel'&&e!=='close')fail(e)}}
function printOrder(row:Row){form.value={...row};items.value=row.items||[];dialog.value='detail'}
function print(){document.body.classList.add('nursery-printing');try{window.print()}finally{document.body.classList.remove('nursery-printing')}}
async function previewImport(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;try{importRows.value=await readNurseryWorkbook(file);dialog.value='import'}catch(e){fail(e)}finally{(event.target as HTMLInputElement).value=''}}
async function importNursery(){if(busy.value)return;busy.value=true;importRunning.value=true;try{for(const row of importRows.value){if(row.import_status!=='待导入')continue;row.import_status='提交中';const {import_status,...payload}=row;try{const response:any=await request('/nursery/inbound',{method:'POST',body:JSON.stringify(payload)});if(response.success===false)throw Error(response.msg);row.import_status='成功'}catch(e:any){row.import_status=e.uncertain?'结果未确认，请核对流水，勿重复导入':`失败：${e.message}`;if(e.uncertain)break}}await load()}finally{busy.value=false;importRunning.value=false}}
async function template(){try{await exportWorkbook([{'苗木名称':'红枫','大类':'苗木','规格':'H3.0m','单位':'株','数量':'100','单价':'150','存放位置':'A区-01'}],'苗圃入库模板.xlsx')}catch(e){fail(e)}}
async function exportRows(){try{await exportWorkbook(filtered.value.map(r=>Object.fromEntries(columns.value.map(c=>[labels[c]||c,r[c]]))),'苗圃台账.xlsx')}catch(e){fail(e)}}
</script>
<template><section class="page"><PageHeader :title="({dashboard:'苗圃看板',inventory:'苗圃库存',inbound:'苗木入库',outbound:'苗木出库',orders:'出库单管理',logs:'苗圃日志',history:'出入库流水',transactions:'出入库流水',settings:'苗圃设置'} as any)[view]" description="管理苗木库存、入出库单据与业务流水。"/>
<div v-if="view==='settings'" class="form-grid"><el-card v-for="(title,t) in {category:'产品大类',location:'存放位置','non-inventory':'非入库商品'}" :key="t"><template #header><b>{{title}}</b><el-button link type="primary" @click="settingEdit(t)">新增</el-button></template><p v-for="(v,index) in settings[t]" :key="index">{{typeof v==='string'?v:`${v.name} · ${v.unit} · ${v.guide_price}`}} <el-button link @click="settingEdit(t,Number(index))">编辑</el-button><el-button link type="danger" @click="settingDelete(t,Number(index))">删除</el-button></p><el-empty v-if="!settings[t].length" description="暂无设置"/></el-card><p class="muted">设置保存在当前浏览器，与原苗圃页面共用。</p></div>
<template v-else-if="view==='outbound'"><div class="panel"><Fields :model="form" :fields="baseFields"/><div class="toolbar"><el-select placeholder="添加库存苗木" filterable :model-value="null" @change="addStock"><el-option v-for="p in stock" :key="p.id" :value="p.id" :label="`${p.name} ${p.spec||''} · 库存 ${p.quantity} ${p.unit}`"/></el-select><el-select placeholder="添加非入库商品" :model-value="null" @change="addNonInventory(settings['non-inventory'][$event])"><el-option v-for="(p,i) in settings['non-inventory']" :key="i" :label="p.name" :value="i"/></el-select><el-button @click="addNonInventory()">自定义非入库项目</el-button></div><el-table :data="items"><el-table-column label="名称" min-width="130"><template #default="{row}"><el-input v-if="row.is_non_inventory" v-model="row.name"/><span v-else>{{row.name}}</span></template></el-table-column><el-table-column v-for="c in ['spec','unit','quantity','price']" :key="c" :label="labels[c]"><template #default="{row}"><el-input v-model="row[c]" :disabled="!row.is_non_inventory&&['spec','unit'].includes(c)"/></template></el-table-column><el-table-column label="库存"><template #default="{row}">{{row.is_non_inventory?'非入库':row.available}}</template></el-table-column><el-table-column label="操作"><template #default="{$index}"><el-button link type="danger" @click="items.splice($index,1)">移除</el-button></template></el-table-column></el-table><p>合计：{{items.reduce((n,r)=>n+(Number(r.quantity)||0)*(Number(r.price)||0),0).toFixed(2)}}</p><el-button type="primary" :loading="busy" @click="submitOutbound">提交出库</el-button></div></template>
<template v-else><template v-if="view==='dashboard'"><div class="form-grid"><el-card v-for="(title,key) in {total_varieties:'在库品种',month_outbound:'本月出库次数',category_count:'在库大类',low_stock:'低库存预警'}" :key="key"><el-statistic :title="title" :value="Number(stats[key]||0)"/></el-card></div><div class="form-grid"><el-card header="分类分布"><p v-for="r in stats.category_distribution" :key="r.category">{{r.category}}：{{r.count}}</p></el-card><el-card header="库存 TOP 5"><p v-for="r in stats.top5" :key="r.name">{{r.name}}：{{r.quantity}}</p></el-card></div></template><div class="toolbar"><el-button v-if="view==='inbound'" type="primary" @click="newInbound">新增入库</el-button><template v-if="view==='inbound'"><el-button @click="template">下载导入模板</el-button><label class="el-button">Excel 导入<input style="display:none" type="file" accept=".xls,.xlsx" @change="previewImport"/></label></template><el-button @click="exportRows">导出 Excel</el-button><router-link v-if="view==='inventory'" to="/nursery/inbound">新增入库</router-link><router-link v-if="['inventory','orders','dashboard'].includes(view)" to="/nursery/outbound">苗木出库</router-link><el-input v-model="search" placeholder="搜索全部记录" clearable/><el-select v-if="['logs','history','transactions'].includes(view)" v-model="type" clearable placeholder="全部类型"><el-option label="入库" value="in"/><el-option label="出库" value="out"/></el-select><el-button @click="load">刷新</el-button></div><el-alert v-if="view==='logs'" title="日志编辑和删除仅修改流水，不调整库存。需要调整出库数量及库存，请进入出库单管理。" type="warning" :closable="false"/><el-table v-loading="loading" :data="pageRows" border><el-table-column v-for="c in columns" :key="c" :prop="c" :label="labels[c]||c" min-width="120" sortable><template #default="{row}">{{displayValue(c,row[c])}}</template></el-table-column><el-table-column v-if="['orders','logs'].includes(view)" label="操作" fixed="right" width="200"><template #default="{row}"><el-button v-if="view==='orders'" link @click="printOrder(row)">详情 / 打印</el-button><el-button link type="primary" @click="view==='orders'?editOrder(row):editLog(row)">编辑</el-button><el-button link type="danger" :disabled="busy" @click="remove(row)">删除</el-button></template></el-table-column></el-table><el-pagination v-model:current-page="page" :page-size="30" :total="filtered.length" layout="total,prev,pager,next"/></template>
<el-dialog v-model="open" :title="({inbound:'苗木入库',order:'编辑出库单',log:'编辑流水（不调整库存）',setting:'设置',detail:'出库单明细',import:'批量入库预览'} as any)[dialog]" width="900px" :close-on-click-modal="false" :before-close="beforeClose"><div v-if="dialog==='import'"><el-alert title="每行独立入库。成功行不会再次提交；失败或结果不确定时请先核对流水。" :closable="false"/><el-table :data="importRows"><el-table-column v-for="c in ['name','spec','quantity','price']" :key="c" :prop="c" :label="labels[c]"><template #default="{row}">{{displayValue(c,row[c])}}</template></el-table-column><el-table-column prop="import_status" label="结果" min-width="200"/></el-table></div><div v-else-if="dialog==='detail'" class="nursery-print"><h2>苗圃出库单 {{form.order_no}}</h2><p>{{form.create_at}} · {{form.operator}} · {{form.destination}}</p><el-table :data="items"><el-table-column v-for="c in ['plant_name','spec','unit','quantity','price','total_price']" :key="c" :prop="c" :label="labels[c]"><template #default="{row}">{{displayValue(c,row[c])}}</template></el-table-column></el-table><p>合计：{{displayValue('total',form.total)}}</p></div><template v-else><Fields :model="form" :fields="fields" :options="options"/><el-table v-if="dialog==='order'" :data="items"><el-table-column prop="plant_name" label="苗木"/><el-table-column prop="spec" label="规格"/><el-table-column v-for="c in ['quantity','price']" :key="c" :label="labels[c]"><template #default="{row}"><el-input v-model="row[c]"/></template></el-table-column></el-table></template><template #footer><el-button :disabled="busy" @click="closeEditor">关闭</el-button><el-button v-if="dialog==='detail'" @click="print">打印</el-button><el-button v-else-if="dialog==='import'" type="primary" :loading="importRunning" :disabled="!importRows.some(r=>r.import_status==='待导入')" @click="importNursery">导入待处理行</el-button><el-button v-else type="primary" :loading="busy" @click="save">保存</el-button></template></el-dialog>
</section></template>
<style>@media print{body.nursery-printing *{visibility:hidden}body.nursery-printing .nursery-print,body.nursery-printing .nursery-print *{visibility:visible}body.nursery-printing .nursery-print{position:absolute;left:0;top:0;width:100%}body.nursery-printing .el-overlay{position:absolute!important;overflow:visible!important}}</style>







