import {describe,it,expect} from 'vitest'
import {parseAttachments,payload,validate,schemas,orderOptionLabel,ocrStatusLabel} from './model'
import {uppercaseMoney,sumMoney,formatMoney} from './money'
describe('core mutation contracts',()=>{
 it('preserves attachment identity and file path when normalizing project attachment records',()=>{expect(parseAttachments({attachments_list:[{id:7,attachment_code:'A-01',file_path:'/uploads/a.pdf',original_filename:'合同.pdf'}]})[0]).toMatchObject({id:7,code:'A-01',url:'/uploads/a.pdf',file_path:'/uploads/a.pdf',name:'合同.pdf'})})
 it('refuses invalid attachment JSON instead of silently erasing attachments',()=>{expect(()=>parseAttachments({attachments:'broken'})).toThrow();expect(()=>parseAttachments({attachments:'{}'})).toThrow()})
 it('preserves exact decimal strings and existing invoice associations',()=>{const result=payload('payments',{id:9,pay_number:'FK9',current_payment_amount:'90071992547409.19',invoice_amount:'0.00',order_id:3,create_at:'2026-09-24 10:20:00',invoices_list:[{id:2}]},[{id:5,url:'/uploads/a.pdf'}],[2,4]);expect(result.current_payment_amount).toBe('90071992547409.19');expect(result.invoice_ids).toEqual([2,4]);expect(result.attachments).toBe('[{"id":5,"url":"/uploads/a.pdf"}]');expect(result.create_at).toBe('2026-09-24 10:20:00');expect(result).not.toHaveProperty('invoices_list')})
 it('never sends relationship objects or stale project display name to order mutation',()=>{const result=payload('orders',{id:1,project_id:9,project_name:'Old name',order_amount:'1.20',pays_list:[{id:1}]},[],[]);expect(result.project_id).toBe(9);expect(result).not.toHaveProperty('project_name');expect(result).not.toHaveProperty('pays_list')})
 it('invoice edit only sends the three writable API fields',()=>{expect(payload('invoices',{id:1,invoice_number:'123',total_amount:'99.01',invoice_category:'1',deductible:'yes',remarks:'note'},[],[])).toEqual({invoice_category:'1',deductible:'yes',remarks:'note'})})
 it('validates required fields and monetary precision without Number coercion',()=>{expect(validate('projects',{project_name:'项目',project_amount:'1.001'})).toContain('两位小数');expect(validate('projects',{project_name:'  '})).toContain('不能为空');expect(validate('projects',{project_name:'项目',project_amount:'0.00'})).toBe('')})
 it('uses actual legacy menu routes for permissions',()=>{expect(schemas.orders?.menu).toBe('/order_pay/base/order_base.html');expect(schemas.invoices?.menu).toBe('/view/material/invoice')})
 it('totals decimal amounts beyond Number safe integer precision without rounding',()=>{expect(sumMoney(['90071992547409.19','0.29','-0.10'])).toBe('90071992547409.38')})
 it('uses material dictionary labels in the payment order picker',()=>{const order={order_number:'D001',project_name:'测试项目',material_name:'001'};expect(orderOptionLabel(order,[{value:'001',label:'水泥'}])).toBe('D001 · 测试项目 · 水泥');expect(order.material_name).toBe('001')})
 it('shows Chinese OCR states while retaining unknown server status information',()=>{expect(ocrStatusLabel('pending')).toBe('待识别');expect(ocrStatusLabel('processing')).toBe('识别中');expect(ocrStatusLabel('success')).toBe('识别成功');expect(ocrStatusLabel('completed')).toBe('识别完成');expect(ocrStatusLabel('failed')).toBe('识别失败');expect(ocrStatusLabel(null)).toBe('未识别');expect(ocrStatusLabel('server_custom')).toBe('server_custom')})
})
describe('print currency',()=>{it.each([['0','零元整'],['0.29','零元贰角玖分'],['10001.01','壹万零壹元零壹分'],['100000001','壹亿零壹元整'],['10.10','壹拾元壹角']])('prints %s accurately',(amount,expected)=>expect(uppercaseMoney(amount)).toBe(expected))})
describe('display currency',()=>{it.each([['80.0','80.00'],['9500','9500.00'],['90071992547409.19','90071992547409.19'],['2.999','3.00'],['-1.2','-1.20'],[null,'—']])('formats %s to two decimals without Number precision loss',(amount,expected)=>expect(formatMoney(amount)).toBe(expected))})
