<script setup lang="ts">
import {ref,onBeforeUnmount,onActivated,onDeactivated} from 'vue';import {useRoute,useRouter} from 'vue-router';import QRCode from 'qrcode';import {request,allRows} from '../../api';import Printorder from './Printorder.vue';import Printpay from './Printpay.vue';import {parseAttachments} from './model';import {uppercaseMoney,formatMoney} from './money'
const currentRoute=useRoute();const route={meta:{...currentRoute.meta},params:{...currentRoute.params}};const router=useRouter(),values=ref<Record<string,any>>({}),qr=ref(''),busy=ref(false),error=ref('');const printDocument=()=>window.print();const isPay=()=>route.meta.coreKind==='payments'
const pageStyle=document.createElement('style');document.head.appendChild(pageStyle);onBeforeUnmount(()=>pageStyle.remove());onActivated(()=>{document.head.appendChild(pageStyle);pageStyle.textContent=isPay()?'@page {size:A5 landscape;margin:0}':'@page {size:A4 portrait;margin:20mm}'});onDeactivated(()=>pageStyle.remove());
async function load(){pageStyle.textContent=isPay()?'@page {size:A5 landscape;margin:0}':'@page {size:A4 portrait;margin:20mm}';busy.value=true;error.value='';try{const materials=await allRows('/dictionary/detail/list',{dic_id:35});const p=(await request(`/${isPay()?'pay':'order'}/${route.params.id}`)).data;const o=isPay()&&p.order_id?(await request(`/order/${p.order_id}`)).data:p;const supplier=isPay()&&p.payee_supplier_id?(await request(`/supplier/${p.payee_supplier_id}`)).data:{};
values.value={'print-date':new Date().toLocaleDateString('sv-SE'),'order-number':o.order_number,'project-name':o.project_name,'material-name':materials.find(x=>String(x.code)===String(o.material_name))?.value||o.material_name,'supplier-name':o.supplier_name,'material-details':o.material_details,'order-amount':formatMoney(o.order_amount),'order-balance':formatMoney(o.order_balance),'cutting-time':o.cutting_time,'arrival-time':o.estimated_arrival_time,'contact-person':o.supplier_contact_person,'contact-phone':o.contact_phone,'material-manager':o.material_manager,'sub-project-manager':o.sub_project_manager,'payment-history':(o.pays_list||[]).map((x:any)=>`${x.pay_number} ${x.payment_status} ¥${formatMoney(x.current_payment_amount)} (${x.create_at||''})`).join('；')||'暂无付款记录','attachment-list':parseAttachments(o).map(x=>x.name||x.filename).join('，')||'无附件','pay-number':p.pay_number,'create-date':p.create_at?.split(' ')[0],'amount-small':formatMoney(p.current_payment_amount),'amount-big':uppercaseMoney(p.current_payment_amount),'payment-purpose':p.payment_purpose,'handler-sign':p.handler,'payer-name':p.payer_supplier_name,'payee-name':p.payee_supplier_name,'bank-name':supplier.bank_name,'bank-account':supplier.account_number,'paid-total':formatMoney(o.paid_amount),'pay-ratio':Number(o.order_amount)>0?(Number(o.paid_amount)/Number(o.order_amount)*100).toFixed(1)+'%':'0%','uuid-text':`UID: ${p.id}-${p.pay_number||p.order_number}`};qr.value=await QRCode.toDataURL(isPay()?`PAY:${p.pay_number}|${p.current_payment_amount}`:`ORDER:${o.order_number}|ID:${o.id}`,{width:isPay()?48:64,margin:0});document.title=isPay()?`付款审批单-${p.pay_number}`:`采购订单审批单-${o.order_number}`
}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
void load();let activatedOnce=false;onActivated(()=>{if(activatedOnce)void load();activatedOnce=true})
</script>
<template><div class="print-page" v-loading="busy"><div class="no-print toolbar"><m-button @click="router.push('/'+route.meta.coreKind+'/'+route.params.id)">返回详情</m-button><m-button type="primary" :disabled="busy||!!error" @click="printDocument">打印单据</m-button></div><m-alert v-if="error" :title="error" type="error" :closable="false"/><m-button v-if="error" @click="load">重新加载</m-button><template v-else-if="!busy"><Printpay v-if="isPay()" :values="values" :qr="qr"/><Printorder v-else :values="values" :qr="qr"/></template></div></template>
<style>@media print{body:has(.print-page) *{visibility:hidden}.print-page,.print-page *{visibility:visible}.print-page{position:absolute;left:0;top:0;width:100%;background:white}.print-page .no-print,.print-page .no-print *{display:none!important}.print-page .print-root{min-height:0!important}.print-page .print-canvas,.print-page .print-container{margin:0!important;box-shadow:none!important}}</style>




