<script setup lang="ts">
import PageHeader from "../../components/PageHeader.vue";
import { computed, nextTick, ref, watch } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { useSystemDraft } from './useSystemDraft'
import { request, allRows } from '../../api'
import { permittedParents, userPayload, editablePayload, safeSelection, type Row } from './helpers'
const props = defineProps<{kind: string}>()
const configs: Record<string, any> = {
 users: { title: '用户管理', api: '/user/', fields: [['username','用户名'],['nickname','昵称'],['mobile','手机号'],['email','邮箱'],['create_at','创建时间','date'],['password','密码','password']], required:['username','nickname'] },
 roles: { title: '角色管理', api: '/role/', fields: [['name','角色名'],['code','角色标识'],['desc','描述']], required:['name','code'] },
 departments: { title: '部门管理', api: '/department/', list:'/department/treetable', fields:[['name','部门名'],['leader','负责人'],['enable','启用','switch'],['pid','上级部门','parent']], required:['name'] },
 rights: { title: '权限管理', api: '/rights/', list:'/rights/treetable', fields:[['name','权限名'],['code','权限标识'],['type','类型','type'],['url','访问地址'],['icon_sign','图标'],['status','启用','switch'],['sort','排序','number'],['open_type','打开方式','open'],['pid','上级权限','parent']], required:['name'] }
}
const config = computed(() => configs[props.kind])
const rows = ref<Row[]>([]), loading = ref(false), busy = ref(false), search = ref(''), page = ref(1), dialog = ref(false), form = ref<Row>({})
const authOpen = ref(false), authLoading = ref(false), authOptions = ref<Row[]>([]), selected = ref<number[]>([]), authId = ref(0), authName = ref(''), tree = ref<any>()
const editBaseline=ref(''), authBaseline=ref('')
const dirty=computed(()=>dialog.value?JSON.stringify(form.value)!==editBaseline.value:authOpen.value?JSON.stringify([...selected.value].sort())!==authBaseline.value:false)
const {allowDiscard,beforeClose}=useSystemDraft(dirty,busy,()=>{dialog.value=false;authOpen.value=false})
const filtered = computed(() => { const term = search.value.toLowerCase(); function filter(items:Row[]):Row[] { return items.flatMap(row => { const children=filter(row.children||[]); return Object.values(row).some(x => typeof x !== 'object' && String(x??'').toLowerCase().includes(term)) ? [row] : children.length ? [{...row,children}] : [] }) }; return term ? filter(rows.value) : rows.value })
const visible = computed(() => filtered.value.slice((page.value-1)*20,page.value*20))
const parents = computed(() => permittedParents(rows.value, form.value.id))
const fields = computed(() => config.value.fields.filter((f:string[]) => f[2] !== 'password' && f[2] !== 'parent'))
const fail = (e:unknown) => ElMessage.error(e instanceof Error ? e.message : String(e))
async function load() { loading.value=true; try { rows.value=await allRows(config.value.list||config.value.api) } catch(e){ fail(e) } finally{loading.value=false} }
watch(() => props.kind, () => { rows.value=[]; page.value=1; search.value=''; dialog.value=false; authOpen.value=false; load() },{immediate:true})
watch(search,()=>page.value=1)
function edit(row?:Row) { form.value=row ? {...editablePayload(row),password:''} : props.kind==='departments'?{enable:true,pid:null}:props.kind==='rights'?{status:true,sort:0,type:'menu',open_type:'_component',pid:null}:{}; editBaseline.value=JSON.stringify(form.value); dialog.value=true }
async function save() { if(busy.value)return; if(config.value.required.some((k:string)=>!String(form.value[k]??'').trim()))return ElMessage.warning('请填写必填项'); busy.value=true; try { const payload=props.kind==='users'?userPayload(form.value):editablePayload(form.value); if(props.kind!=='users')delete payload.password; if(!payload.id)delete payload.id; await request(config.value.api+(form.value.id||''),{method:form.value.id?'PUT':'POST',body:JSON.stringify(payload)}); dialog.value=false; ElMessage.success('保存成功'); await load() }catch(e){fail(e)}finally{busy.value=false} }
async function remove(row:Row) { if(busy.value)return; try {await ElMessageBox.confirm(`确定删除“${row.name||row.username}”？`,'删除确认',{type:'warning'}); busy.value=true; await request(config.value.api+row.id,{method:'DELETE'}); await load(); ElMessage.success('删除成功')}catch(e){if(e!=='cancel'&&e!=='close')fail(e)}finally{busy.value=false} }
async function authorize(row:Row) { authId.value=row.id; authName.value=row.name||row.username; authOptions.value=[]; selected.value=[]; authOpen.value=true; authLoading.value=true; try { const isUser=props.kind==='users'; const [options,owned]=await Promise.all([isUser?allRows('/role/'):request<Row[]>('/rights/tree').then(r=>r.data),request<number[]>(`${isUser?'/user/user_role/':'/role/role_rights/'}${row.id}`)]); authOptions.value=options; selected.value=safeSelection(owned.data,options); authBaseline.value=JSON.stringify([...selected.value].sort()); await nextTick(); tree.value?.setCheckedKeys(selected.value) }catch(e){fail(e);authOpen.value=false}finally{authLoading.value=false} }
async function saveAuthorization(){if(busy.value||authLoading.value)return; busy.value=true;try{ const ids=props.kind==='users'?selected.value:tree.value.getCheckedKeys(); await request(`${props.kind==='users'?'/user/user_role/':'/role/role_rights/'}${authId.value}`,{method:'PUT',body:JSON.stringify({rights_ids:ids.join(',')})}); authOpen.value=false; ElMessage.success('授权成功'); await load() }catch(e){fail(e)}finally{busy.value=false}}
</script>
<template>
 <section class="page"><PageHeader :title="config.title" description="维护系统基础信息与访问权限"><el-button type="primary" @click="edit()">新增</el-button></PageHeader>
 <div class="panel"><div class="toolbar"><el-input v-model="search" placeholder="搜索名称、标识或其他字段" clearable style="max-width:340px"/><el-button @click="load" :loading="loading">刷新</el-button></div>
 <el-table :data="visible" row-key="id" default-expand-all v-loading="loading" empty-text="暂无数据"><el-table-column prop="id" label="ID" width="80"/><el-table-column v-for="field in fields" :key="field[0]" :prop="field[0]" :label="field[1]" min-width="140"><template #default="{row}"><el-tag v-if="field[2]==='switch'" :type="row[field[0]]?'success':'info'">{{row[field[0]]?'启用':'停用'}}</el-tag><span v-else>{{row[field[0]]??'—'}}</span></template></el-table-column><el-table-column label="操作" fixed="right" width="210"><template #default="{row}"><el-button link type="primary" @click="edit(row)">编辑</el-button><el-button v-if="kind==='users'||kind==='roles'" link type="primary" @click="authorize(row)">授权</el-button><el-button link type="danger" :disabled="busy" @click="remove(row)">删除</el-button></template></el-table-column></el-table>
 <el-pagination v-model:current-page="page" :page-size="20" :total="filtered.length" layout="total, prev, pager, next"/></div>
 <el-dialog v-model="dialog" :title="(form.id?'编辑':'新增')+config.title" width="620px" :close-on-click-modal="false" :before-close="beforeClose"><el-form label-width="100px" @submit.prevent="save">
 <el-form-item v-for="field in config.fields" :key="field[0]" :label="field[1]" :required="config.required.includes(field[0])"><el-switch v-if="field[2]==='switch'" v-model="form[field[0]]"/><el-select v-else-if="field[2]==='parent'" v-model="form.pid" clearable placeholder="顶级（无上级）"><el-option v-for="parent in parents" :key="parent.id" :value="parent.id" :label="`${parent.name} (#${parent.id})`"/></el-select><el-select v-else-if="field[2]==='type'" v-model="form.type"><el-option label="菜单" value="menu"/><el-option label="路由" value="path"/><el-option label="权限" value="auth"/></el-select><el-select v-else-if="field[2]==='open'" v-model="form.open_type"><el-option label="默认方式" value="_component"/><el-option label="新窗口" value="_blank"/></el-select><el-input-number v-else-if="field[2]==='number'" v-model="form[field[0]]" :precision="0"/><el-date-picker v-else-if="field[2]==='date'" v-model="form[field[0]]" type="datetime" value-format="YYYY-MM-DD HH:mm:ss"/><el-input v-else v-model="form[field[0]]" :type="field[2]==='password'?'password':'text'" :show-password="field[2]==='password'" autocomplete="off" :placeholder="field[2]==='password'?(form.id?'留空保留原密码':'留空使用默认密码 123456'):''"/></el-form-item></el-form><template #footer><el-button :disabled="busy" @click="allowDiscard">取消</el-button><el-button type="primary" :loading="busy" @click="save">保存</el-button></template></el-dialog>
 <el-dialog v-model="authOpen" :title="`${authName} · ${kind==='users'?'角色分配':'权限分配'}`" width="540px" :close-on-click-modal="false" :before-close="beforeClose"><div v-loading="authLoading"><p class="muted">仅保存明确选中的项目；不会自动授予新建角色。</p><el-checkbox-group v-if="kind==='users'" v-model="selected"><el-checkbox v-for="role in authOptions" :key="role.id" :value="role.id">{{role.name}} ({{role.code}})</el-checkbox></el-checkbox-group><el-tree v-else ref="tree" :data="authOptions" node-key="id" :props="{label:'title',children:'children'}" show-checkbox check-strictly default-expand-all :default-checked-keys="selected" @check="(_:unknown,state:any)=>selected=state.checkedKeys"/></div><template #footer><el-button :disabled="busy" @click="allowDiscard">取消</el-button><el-button type="primary" :loading="busy" :disabled="authLoading" @click="saveAuthorization">保存授权</el-button></template></el-dialog></section>
</template>
