<script setup lang="ts">
import {ref,onMounted} from 'vue';import {useRoute,useRouter} from 'vue-router';import {request} from '../api';import {config,money,type Kind,type RecordData} from '../model';import {label,can} from '../store';import AttachmentPanel from '../components/AttachmentPanel.vue';
const route=useRoute();const router=useRouter();const kind=route.params.kind as Kind;const meta=config[kind];const row=ref<RecordData|null>(null);const error=ref('');const loading=ref(false);
const relationLabels:Record<string,string>={project_id:'project_name',supplier_id:'supplier_name',order_id:'order_number',payer_supplier_id:'payer_supplier_name',payee_supplier_id:'payee_supplier_name'};
async function load(){if(!can(kind))return;loading.value=true;error.value='';try{row.value=(await request(`/${kind}/${route.params.id}`)).data}catch(e){error.value=(e as Error).message}finally{loading.value=false}}
function back(){router.push({path:`/${kind}`,query:route.query})}onMounted(load);
</script><template><main class="page detail-page"><van-nav-bar :title="`${meta.title}详情`" left-text="返回" left-arrow @click-left="back"/><van-empty v-if="!can(kind)" description="当前账号无此业务菜单"/><van-loading v-else-if="loading" class="center-loading"/><div v-else-if="error" class="error-panel" role="alert">{{error}}<van-button @click="load">重新加载</van-button></div><template v-else-if="row">
 <section class="detail-hero"><div class="card-top"><span class="eyebrow">{{kind.toUpperCase()}} · {{row.id}}</span><span v-if="meta.status" class="status-pill">{{label(meta.dict,row[meta.status])}}</span></div><h1>{{row[meta.name]}}</h1><p>{{kind==='project'?row.project_full_name:row.project_name}}</p><small>{{kind==='project'?'合同金额':kind==='order'?'订单金额':'本次付款'}}</small><strong class="hero-money">¥ {{money(row[meta.amount])}}</strong></section>
 <div class="detail-actions"><router-link :to="{path:`/${kind}/${row.id}/edit`,query:route.query}"><van-icon name="edit"/> 编辑{{meta.title}}</router-link><router-link v-if="kind==='project'&&can('order')" :to="`/order?project_id=${row.id}`"><van-icon name="orders-o"/> 关联订单</router-link><router-link v-if="kind==='order'&&can('pay')" :to="`/pay?order_id=${row.id}`"><van-icon name="balance-list-o"/> 关联付款</router-link></div>
 <h2 class="section-title">基本信息</h2><van-cell-group inset><van-cell v-for="f in meta.fields.filter(f=>f.key!==meta.name&&f.key!==meta.amount)" :key="f.key" :title="f.label" :value="f.type==='select'?label(f.dict,row[f.key]):f.type==='money'?money(row[f.key]):f.type==='relation'?(row[relationLabels[f.key]]||row[f.key]||'—'):(row[f.key]||'—')"/><van-cell title="创建时间" :value="row.create_at"/></van-cell-group>
 <template v-if="kind==='order'"><h2 class="section-title">付款记录</h2><van-cell-group inset><van-cell title="已登记付款单" :value="`${row.pays_count||0} 笔`"/><van-cell v-for="p in (row.pays_list||[])" :key="p.id" :title="p.pay_number" :label="label('fkzt',p.payment_status)" :value="`¥ ${money(p.current_payment_amount)}`" :is-link="can('pay')" @click="can('pay')&&router.push(`/pay/${p.id}`)"/></van-cell-group><van-button v-if="can('pay')" block plain class="section-button" @click="router.push(`/pay/new?order_id=${row.id}`)">为此订单新增付款</van-button></template>
 <template v-if="kind==='pay'&&row.invoices_list?.length"><h2 class="section-title">已关联发票</h2><van-cell-group inset><van-cell v-for="invoice in row.invoices_list" :key="invoice.id" :title="invoice.invoice_number||'发票'" :label="invoice.seller_name" :value="`¥ ${money(invoice.total_amount)}`"/></van-cell-group><p class="empty-hint">发票关联请在电脑端管理。</p></template>
 <AttachmentPanel :model-value="row.attachments_list||[]" :kind="kind" readonly/>
 </template></main></template>
