<script setup lang="ts">
defineOptions({name:'BusinessList'});
import {computed,ref,watch,onActivated,onDeactivated} from 'vue';import {useRoute} from 'vue-router';import {config,type Kind} from '../model';import {request,query} from '../api';import {listState,session,revisions,can} from '../store';import RecordCard from '../components/RecordCard.vue';
const route=useRoute();const kind=route.params.kind as Kind;const meta=config[kind];const key=route.path;const state=listState[key]||(listState[key]={search:'',status:'',rows:[],page:0,total:0,scroll:0});const loading=ref(false);const error=ref('');const active=ref(false);let stamp=0;let seen=-1;let lastFilter='';
const finished=computed(()=>state.page>0&&state.rows.length>=state.total);const options=computed(()=>[{text:'全部状态',value:''},...(session.dicts[meta.dict||'']||[]).map(x=>({text:x.label,value:x.value}))]);
async function load(reset=false){if(loading.value&&!reset)return;const turn=++stamp;loading.value=true;error.value='';if(reset){state.rows=[];state.page=0;state.total=0}try{const page=reset?1:state.page+1;const r=await request(`/${kind}/?`+query({page,limit:15,[meta.search]:state.search,...(meta.status?{[meta.status]:state.status}:{}),project_id:route.query.project_id,order_id:route.query.order_id}));if(turn!==stamp)return;state.rows=reset?r.data:[...state.rows,...r.data];state.page=page;state.total=r.count||0;seen=revisions[kind]}catch(e){if(turn===stamp)error.value=(e as Error).message}finally{if(turn===stamp)loading.value=false}}
onActivated(()=>{active.value=true;const f=JSON.stringify(route.query);if(seen!==revisions[kind]||lastFilter!==f||!state.page){lastFilter=f;load(true)}else requestAnimationFrame(()=>window.scrollTo(0,state.scroll))});onDeactivated(()=>{active.value=false;state.scroll=window.scrollY;stamp++;loading.value=false});watch(()=>route.query,()=>{if(active.value){lastFilter=JSON.stringify(route.query);load(true)}});
</script><template><main class="page list-page"><header class="page-header"><div><span class="eyebrow">BUSINESS / {{kind.toUpperCase()}}</span><h1>{{meta.title}}管理</h1></div><router-link v-if="can(kind)" :to="{path:`/${kind}/new`,query:route.query}" class="round-add" :aria-label="`新增${meta.title}`"><van-icon name="plus" size="24"/></router-link></header>
 <template v-if="can(kind)"><van-search v-model="state.search" :placeholder="`搜索${meta.title}${kind==='project'?'名称':'编号'}`" shape="round" background="transparent" @search="load(true)" @clear="load(true)" show-action><template #action><button class="search-button" @click="load(true)">搜索</button></template></van-search>
 <div v-if="route.query.project_id||route.query.order_id" class="scope-filter"><van-icon name="filter-o"/> 已筛选关联{{route.query.project_id?'项目':'订单'}} <router-link :to="`/${kind}`">查看全部</router-link></div>
 <van-dropdown-menu v-if="meta.dict" class="status-filter"><van-dropdown-item v-model="state.status" :options="options" @change="load(true)"/></van-dropdown-menu>
 <div class="list-caption"><span>共 {{state.total}} 条记录</span><button @click="load(true)"><van-icon name="replay"/> 刷新</button></div>
 <div v-if="error" class="error-panel" role="alert">{{error}}<van-button size="small" @click="load(state.page===0)">重新加载</van-button></div>
 <RecordCard v-for="row in state.rows" :key="row.id" :kind="kind" :row="row"/>
 <van-loading v-if="loading" class="center-loading"/><van-empty v-else-if="!state.rows.length&&!error" description="没有符合条件的记录"/>
 <van-button v-else-if="!finished&&!loading&&!error" block plain class="more-button" @click="load()">加载更多</van-button><p v-else-if="finished&&state.rows.length" class="end-note">已显示全部记录</p></template><van-empty v-else description="当前账号无此业务菜单"/>
</main></template>
